import { Injectable } from '@angular/core';
import { HttpClient, HttpHeaders, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs/Observable';
 
@Injectable({
  providedIn: 'root'
})
export class RatesService {
  url = "https://customer.r2logistics.com/Services/RatingEngineService.svc/json/RateShipment";
  constructor(private http: HttpClient) { }
  
  // postRates(objRate: Object): Observable<HttpResponse<Object>> {
  //   let httpHeaders = new HttpHeaders({
  //        'Content-Type' : 'application/json'
  //   });    
  //   return this.http.post<Object>(this.url, objRate,
  //       {
  //         headers: httpHeaders,
  //         observe: 'response'
  //       }
  //   );
  // }    



  postRates(objRate: Object): Observable<HttpResponse<Object>> {
      let httpHeaders = new HttpHeaders({
           'Content-Type' : 'application/json'
           ,
           'Access-Control-Allow-Origin' : '*'
          //  ,
          //   'Access-Control-Allow-Methods' : 'POST',
          //   'Access-Control-Allow-Headers' : 'Content-Type',
          //   'Access-Control-Allow-Credentials': 'true'
      });    
      return this.http.post<Object>(this.url, {
            "ClientID":27784,"ProfileID":41887,"Products":[{"Weight":"100","ProductClass":"50","Pieces":"1","Pallets":0,"PackageTypeID":4,"Length":"48","Height":"48","Width":"48","PCF":"1.56","Status":1}],"SourcePostalCode":"60001","SourceCityID":84846,"SourceStateID":63,"SourceCountryID":1,"SourceCountry":"USA","SourceStateCode":"IL ","SourceCityName":"ALDEN                         ","DestPostalCode":"30001","DestCityID":353249,"DestStateID":11,"DestCountryID":1,"DestCountry":"USA","DestStateCode":"GA ","DestCityName":"Austell","ShipmentDate":"/Date(1592784000000)/","Accessorials":[],"AccessorialCodes":[],"TopN":10,"ServiceLevelGrops":[],"ServiceLevels":[],"ServiceLevelCodes":[],"EquipmentList":[],"IsDebug":false,"IsSuperAdmin":false,"AccessorialIDs":[],"SkeepCalculatePPS":false,"Origin":"60001,ALDEN                         ,ILLINOIS                 ","Destination":"30001,Austell,GEORGIA                  "
           },
          {
            headers: httpHeaders,
            observe: 'response'
          }
      );
    }    

    getCountries(){
      return this.http.get('https://customer.r2logistics.com/Services/MASCityStatePostalService.svc/json/GetCountryList?_=1592973456198')
    }

  getRates(){


    return [
      {
        "Accessorials": [],
        "ApiCallDuration": "00:00:00",
        "BenchMarkCost": null,
        "CarrierConnectRequestResponseString": null,
        "CarrierCost": 0,
        "CarrierCostWithOutTrueCost": 0,
        "CarrierID": "UPGF",
        "CarrierName": "UPS FREIGHT",
        "CarrierType": "Direct",
        "CarrierTypeID": 2,
        "CostWithCustomerPercentage": 0,
        "CostWithCustomerPercentageWithOutTrueCost": 0,
        "CustomerCost": 0,
        "DeficitCharge": 0,
        "DeficitWeight": 0,
        "DestTerminalAddress1": "1311 W 15TH ST",
        "DestTerminalAddress2": "-",
        "DestTerminalCity": "RIVIERA BEACH",
        "DestTerminalCode": "WPB",
        "DestTerminalContactName": "-",
        "DestTerminalContactTitle": "SERVICE CENTER MANAGER",
        "DestTerminalEmail": "-",
        "DestTerminalFaxNo": "561-863-8844",
        "DestTerminalFreePhone": "000-000-0000",
        "DestTerminalName": "WEST PALM BEACH",
        "DestTerminalPhoneNo": "561-863-2900",
        "DestTerminalState": "FL",
        "DestTerminalZip": "33404",
        "DestTerminalZipCode": "33404",
        "Discount": 0,
        "DiscountID": 0,
        "DiscountRate": 0,
        "EquipmentCharges": null,
        "Equipments": null,
        "ExcludeReason": "",
        "FreightCost": 0,
        "FuelCost": 0,
        "FuelRate": 0,
        "GrossAmount": 0,
        "IsClientGainShare": false,
        "IsExcluded": true,
        "IsMinimumApplied": false,
        "IsVendorPortalRate": false,
        "LaneID": 697733,
        "LaneName": "UPGF - GUA PM - US-US - BLANKET API",
        "LaneWiseMiles": 1230,
        "MaxHeightShipmentLimit": "Max Height :8 Feet",
        "MaxLenghtShipmentLimit": "Max Length :25 linear Feet",
        "Miles": 1230,
        "MinAmount": 0,
        "ModeType": null,
        "NewInsuranceCost": 1000,
        "OldInsuranceCost": 1000,
        "OriginTerminalAddress1": "3275 MILLER PARK S",
        "OriginTerminalAddress2": "-",
        "OriginTerminalCity": "GARLAND",
        "OriginTerminalCode": "GAR",
        "OriginTerminalContactName": "-",
        "OriginTerminalContactTitle": "SERVICE CENTER MANAGER",
        "OriginTerminalEmail": "-",
        "OriginTerminalFaxNo": "972-487-0114",
        "OriginTerminalFreePhone": "000-000-0000",
        "OriginTerminalName": "GARLAND",
        "OriginTerminalPhoneNo": "972-487-8267",
        "OriginTerminalState": "TX",
        "OriginTerminalZip": "75042",
        "OriginTerminalZipCode": "75042",
        "PaymentType": "3rd Party",
        "Products": [
          {
            "FAKClass": 0,
            "HazMat": false,
            "Height": 48,
            "Length": 48,
            "NmfcNumber": null,
            "PackageType": null,
            "PackageTypeID": null,
            "Pallets": 0,
            "Pieces": 1,
            "ProductClass": 50,
            "ProductCost": 0,
            "ProductDescription": null,
            "RateBase": 0,
            "Stackable": false,
            "Weight": 1000,
            "Width": 48
          }
        ],
        "ProfileID": 11868,
        "QuoteNumber": "",
        "RateType": "CarrierRateService",
        "RatingMarkUp": null,
        "RatingResultId": 57060342,
        "ReferenceNo": 5,
        "Remarks": "UPGF is not rated for EXP service level.",
        "SAASQuoteNumber": 61359355,
        "SaasBrokerCarrierCode": null,
        "SaasBrokerCarrierName": null,
        "SaasServiceLevelCode": "EXP",
        "ServiceLevel": "Guranteed PM",
        "ServiceLevelCode": null,
        "ShowTrueCost": false,
        "StatusCode": 0,
        "TariffName": null,
        "TotalAccCost": 0,
        "TotalAccCostWithOutTrueCost": 0,
        "TotalCost": 0,
        "TotalCostWithCustCostWithOutTrueCost": 0,
        "TotalCostWithOutTrueCost": 0,
        "TotalShipmentCostWithCustomerCost": 0,
        "TransitTime": "3",
        "UsedRatingFuel": {
          "EffectiveFrom": "/Date(662706000000-0500)/",
          "EffectiveTo": "/Date(662706000000-0500)/",
          "FuelLevel": null,
          "FuelRate": 0,
          "FuelRateType": "0",
          "MaxRate": 0,
          "Message": "",
          "MinRate": 0
        },
        "UsedRatingWeeklyFuel": null,
        "ZoneAreaID": 0,
        "ZoneID": 0,
        "ZoneRateID": 0
      },
      {
        "Accessorials": [],
        "ApiCallDuration": "00:00:00.2499961",
        "BenchMarkCost": null,
        "CarrierConnectRequestResponseString": null,
        "CarrierCost": 0,
        "CarrierCostWithOutTrueCost": 0,
        "CarrierID": "SMTL",
        "CarrierName": "SOUTHWESTERN MOTOR TRANSPORT",
        "CarrierType": "",
        "CarrierTypeID": 2,
        "CostWithCustomerPercentage": 0,
        "CostWithCustomerPercentageWithOutTrueCost": 0,
        "CustomerCost": 0,
        "DeficitCharge": 0,
        "DeficitWeight": 0,
        "DestTerminalAddress1": "",
        "DestTerminalAddress2": "",
        "DestTerminalCity": "",
        "DestTerminalCode": "",
        "DestTerminalContactName": "",
        "DestTerminalContactTitle": "",
        "DestTerminalEmail": "",
        "DestTerminalFaxNo": "",
        "DestTerminalFreePhone": "",
        "DestTerminalName": "",
        "DestTerminalPhoneNo": "",
        "DestTerminalState": "",
        "DestTerminalZip": "",
        "DestTerminalZipCode": "",
        "Discount": 0,
        "DiscountID": 0,
        "DiscountRate": 0,
        "EquipmentCharges": null,
        "Equipments": null,
        "ExcludeReason": "",
        "FreightCost": 0,
        "FuelCost": 0,
        "FuelRate": 0,
        "GrossAmount": 0,
        "IsClientGainShare": false,
        "IsExcluded": true,
        "IsMinimumApplied": false,
        "IsVendorPortalRate": false,
        "LaneID": 1601734,
        "LaneName": "SOUTHWESTERN MOTOR TRANSPORT - STD - US-US - BLANKET API",
        "LaneWiseMiles": 1230,
        "MaxHeightShipmentLimit": null,
        "MaxLenghtShipmentLimit": null,
        "Miles": 1230,
        "MinAmount": 0,
        "ModeType": null,
        "NewInsuranceCost": 0,
        "OldInsuranceCost": 0,
        "OriginTerminalAddress1": "",
        "OriginTerminalAddress2": "",
        "OriginTerminalCity": "",
        "OriginTerminalCode": "",
        "OriginTerminalContactName": "",
        "OriginTerminalContactTitle": "",
        "OriginTerminalEmail": "",
        "OriginTerminalFaxNo": "",
        "OriginTerminalFreePhone": "",
        "OriginTerminalName": "",
        "OriginTerminalPhoneNo": "",
        "OriginTerminalState": "",
        "OriginTerminalZip": "",
        "OriginTerminalZipCode": "",
        "PaymentType": "Prepaid",
        "Products": [
          {
            "FAKClass": 50,
            "HazMat": false,
            "Height": 48,
            "Length": 48,
            "NmfcNumber": null,
            "PackageType": null,
            "PackageTypeID": null,
            "Pallets": 0,
            "Pieces": 1,
            "ProductClass": 50,
            "ProductCost": 0,
            "ProductDescription": null,
            "RateBase": 0,
            "Stackable": false,
            "Weight": 1000,
            "Width": 48
          }
        ],
        "ProfileID": 11868,
        "QuoteNumber": "",
        "RateType": "CarrierRateService",
        "RatingMarkUp": null,
        "RatingResultId": 57060343,
        "ReferenceNo": 2,
        "Remarks": "SMT does not provide service for this city, WEST PALM BEACH FL.",
        "SAASQuoteNumber": 61359355,
        "SaasBrokerCarrierCode": null,
        "SaasBrokerCarrierName": null,
        "SaasServiceLevelCode": "STD",
        "ServiceLevel": "Standard",
        "ServiceLevelCode": null,
        "ShowTrueCost": false,
        "StatusCode": 0,
        "TariffName": null,
        "TotalAccCost": 0,
        "TotalAccCostWithOutTrueCost": 0,
        "TotalCost": 0,
        "TotalCostWithCustCostWithOutTrueCost": 0,
        "TotalCostWithOutTrueCost": 0,
        "TotalShipmentCostWithCustomerCost": 0,
        "TransitTime": "9",
        "UsedRatingFuel": {
          "EffectiveFrom": "/Date(662706000000-0500)/",
          "EffectiveTo": "/Date(662706000000-0500)/",
          "FuelLevel": null,
          "FuelRate": 0,
          "FuelRateType": "0",
          "MaxRate": 0,
          "Message": "",
          "MinRate": 0
        },
        "UsedRatingWeeklyFuel": null,
        "ZoneAreaID": 0,
        "ZoneID": 0,
        "ZoneRateID": 0
      },
      {
        "Accessorials": [],
        "ApiCallDuration": "00:00:00",
        "BenchMarkCost": null,
        "CarrierConnectRequestResponseString": null,
        "CarrierCost": 0,
        "CarrierCostWithOutTrueCost": 0,
        "CarrierID": "DAFG",
        "CarrierName": "DAYTON FREIGHT LINES          ",
        "CarrierType": "",
        "CarrierTypeID": 2,
        "CostWithCustomerPercentage": 0,
        "CostWithCustomerPercentageWithOutTrueCost": 0,
        "CustomerCost": 0,
        "DeficitCharge": 0,
        "DeficitWeight": 0,
        "DestTerminalAddress1": "",
        "DestTerminalAddress2": "",
        "DestTerminalCity": "",
        "DestTerminalCode": "",
        "DestTerminalContactName": "",
        "DestTerminalContactTitle": "",
        "DestTerminalEmail": "",
        "DestTerminalFaxNo": "",
        "DestTerminalFreePhone": "",
        "DestTerminalName": "",
        "DestTerminalPhoneNo": "",
        "DestTerminalState": "",
        "DestTerminalZip": "",
        "DestTerminalZipCode": "",
        "Discount": 0,
        "DiscountID": 0,
        "DiscountRate": 0,
        "EquipmentCharges": null,
        "Equipments": null,
        "ExcludeReason": "",
        "FreightCost": 0,
        "FuelCost": 0,
        "FuelRate": 0,
        "GrossAmount": 0,
        "IsClientGainShare": false,
        "IsExcluded": true,
        "IsMinimumApplied": false,
        "IsVendorPortalRate": false,
        "LaneID": 332213,
        "LaneName": "DAYTON - STD - US-US - BLANKET API",
        "LaneWiseMiles": 1230,
        "MaxHeightShipmentLimit": "Max Height :12 Feet",
        "MaxLenghtShipmentLimit": "Max Length :15 linear Feet",
        "Miles": 1230,
        "MinAmount": 0,
        "ModeType": null,
        "NewInsuranceCost": 1000,
        "OldInsuranceCost": 500,
        "OriginTerminalAddress1": "",
        "OriginTerminalAddress2": "",
        "OriginTerminalCity": "",
        "OriginTerminalCode": "",
        "OriginTerminalContactName": "",
        "OriginTerminalContactTitle": "",
        "OriginTerminalEmail": "",
        "OriginTerminalFaxNo": "",
        "OriginTerminalFreePhone": "",
        "OriginTerminalName": "",
        "OriginTerminalPhoneNo": "",
        "OriginTerminalState": "",
        "OriginTerminalZip": "",
        "OriginTerminalZipCode": "",
        "PaymentType": "3rd Party Prepaid",
        "Products": [
          {
            "FAKClass": 0,
            "HazMat": false,
            "Height": 48,
            "Length": 48,
            "NmfcNumber": null,
            "PackageType": null,
            "PackageTypeID": null,
            "Pallets": 0,
            "Pieces": 1,
            "ProductClass": 50,
            "ProductCost": 0,
            "ProductDescription": null,
            "RateBase": 0,
            "Stackable": false,
            "Weight": 1000,
            "Width": 48
          }
        ],
        "ProfileID": 11868,
        "QuoteNumber": "",
        "RateType": "CarrierRateService",
        "RatingMarkUp": null,
        "RatingResultId": 57060344,
        "ReferenceNo": 7,
        "Remarks": "At least one of the points must be a direct serviced point of Dayton Freight Lines. Please call customer service at 800.860.5102 or your local service center.\r\nThe freight terms selected is prepaid and the shipper is a non-direct point, please either change the selected terms or call the Dayton Freight Pricing department at 800.860.5102",
        "SAASQuoteNumber": 61359355,
        "SaasBrokerCarrierCode": null,
        "SaasBrokerCarrierName": null,
        "SaasServiceLevelCode": "STD",
        "ServiceLevel": "Standard",
        "ServiceLevelCode": null,
        "ShowTrueCost": false,
        "StatusCode": 0,
        "TariffName": null,
        "TotalAccCost": 0,
        "TotalAccCostWithOutTrueCost": 0,
        "TotalCost": 0,
        "TotalCostWithCustCostWithOutTrueCost": 0,
        "TotalCostWithOutTrueCost": 0,
        "TotalShipmentCostWithCustomerCost": 0,
        "TransitTime": "9",
        "UsedRatingFuel": {
          "EffectiveFrom": "/Date(662706000000-0500)/",
          "EffectiveTo": "/Date(662706000000-0500)/",
          "FuelLevel": null,
          "FuelRate": 0,
          "FuelRateType": "0",
          "MaxRate": 0,
          "Message": "",
          "MinRate": 0
        },
        "UsedRatingWeeklyFuel": null,
        "ZoneAreaID": 0,
        "ZoneID": 0,
        "ZoneRateID": 0
      },
      {
        "Accessorials": [],
        "ApiCallDuration": "00:00:00.1875116",
        "BenchMarkCost": null,
        "CarrierConnectRequestResponseString": null,
        "CarrierCost": 0,
        "CarrierCostWithOutTrueCost": 0,
        "CarrierID": "DPHE",
        "CarrierName": "DEPENDABLE HIGHWAY EXPRESS",
        "CarrierType": "",
        "CarrierTypeID": 2,
        "CostWithCustomerPercentage": 0,
        "CostWithCustomerPercentageWithOutTrueCost": 0,
        "CustomerCost": 0,
        "DeficitCharge": 0,
        "DeficitWeight": 0,
        "DestTerminalAddress1": "",
        "DestTerminalAddress2": "",
        "DestTerminalCity": "",
        "DestTerminalCode": "",
        "DestTerminalContactName": "",
        "DestTerminalContactTitle": "",
        "DestTerminalEmail": "",
        "DestTerminalFaxNo": "",
        "DestTerminalFreePhone": "",
        "DestTerminalName": "",
        "DestTerminalPhoneNo": "",
        "DestTerminalState": "",
        "DestTerminalZip": "",
        "DestTerminalZipCode": "",
        "Discount": 0,
        "DiscountID": 0,
        "DiscountRate": 0,
        "EquipmentCharges": null,
        "Equipments": null,
        "ExcludeReason": "",
        "FreightCost": 0,
        "FuelCost": 0,
        "FuelRate": 0,
        "GrossAmount": 0,
        "IsClientGainShare": false,
        "IsExcluded": true,
        "IsMinimumApplied": false,
        "IsVendorPortalRate": false,
        "LaneID": 1614709,
        "LaneName": "DPHE - BLANKET - US - US",
        "LaneWiseMiles": 1230,
        "MaxHeightShipmentLimit": "Max Height :8 Feet",
        "MaxLenghtShipmentLimit": "Max Length :15 linear Feet",
        "Miles": 1230,
        "MinAmount": 0,
        "ModeType": null,
        "NewInsuranceCost": 5000,
        "OldInsuranceCost": 100,
        "OriginTerminalAddress1": "",
        "OriginTerminalAddress2": "",
        "OriginTerminalCity": "",
        "OriginTerminalCode": "",
        "OriginTerminalContactName": "",
        "OriginTerminalContactTitle": "",
        "OriginTerminalEmail": "",
        "OriginTerminalFaxNo": "",
        "OriginTerminalFreePhone": "",
        "OriginTerminalName": "",
        "OriginTerminalPhoneNo": "",
        "OriginTerminalState": "",
        "OriginTerminalZip": "",
        "OriginTerminalZipCode": "",
        "PaymentType": "Prepaid",
        "Products": [
          {
            "FAKClass": 0,
            "HazMat": false,
            "Height": 48,
            "Length": 48,
            "NmfcNumber": null,
            "PackageType": null,
            "PackageTypeID": null,
            "Pallets": 0,
            "Pieces": 1,
            "ProductClass": 50,
            "ProductCost": 0,
            "ProductDescription": null,
            "RateBase": 0,
            "Stackable": false,
            "Weight": 1000,
            "Width": 48
          }
        ],
        "ProfileID": 11868,
        "QuoteNumber": "",
        "RateType": "CarrierRateService",
        "RatingMarkUp": null,
        "RatingResultId": 57060345,
        "ReferenceNo": 1,
        "Remarks": "Origin is not a direct service point, Please contact our 3PL,  Dependable Logistics Solutions \"DLS\" for a rate estimate at dlsrate@godependable.com or call  800-924-4744.",
        "SAASQuoteNumber": 61359355,
        "SaasBrokerCarrierCode": null,
        "SaasBrokerCarrierName": null,
        "SaasServiceLevelCode": "STD",
        "ServiceLevel": "Standard",
        "ServiceLevelCode": null,
        "ShowTrueCost": false,
        "StatusCode": 0,
        "TariffName": null,
        "TotalAccCost": 0,
        "TotalAccCostWithOutTrueCost": 0,
        "TotalCost": 0,
        "TotalCostWithCustCostWithOutTrueCost": 0,
        "TotalCostWithOutTrueCost": 0,
        "TotalShipmentCostWithCustomerCost": 0,
        "TransitTime": "9",
        "UsedRatingFuel": {
          "EffectiveFrom": "/Date(662706000000-0500)/",
          "EffectiveTo": "/Date(662706000000-0500)/",
          "FuelLevel": null,
          "FuelRate": 0,
          "FuelRateType": "0",
          "MaxRate": 0,
          "Message": "",
          "MinRate": 0
        },
        "UsedRatingWeeklyFuel": null,
        "ZoneAreaID": 0,
        "ZoneID": 0,
        "ZoneRateID": 0
      },
      {
        "Accessorials": [],
        "ApiCallDuration": "00:00:00",
        "BenchMarkCost": null,
        "CarrierConnectRequestResponseString": null,
        "CarrierCost": 0,
        "CarrierCostWithOutTrueCost": 0,
        "CarrierID": "DAFG",
        "CarrierName": "DAYTON FREIGHT LINES          ",
        "CarrierType": "",
        "CarrierTypeID": 2,
        "CostWithCustomerPercentage": 0,
        "CostWithCustomerPercentageWithOutTrueCost": 0,
        "CustomerCost": 0,
        "DeficitCharge": 0,
        "DeficitWeight": 0,
        "DestTerminalAddress1": "",
        "DestTerminalAddress2": "",
        "DestTerminalCity": "",
        "DestTerminalCode": "",
        "DestTerminalContactName": "",
        "DestTerminalContactTitle": "",
        "DestTerminalEmail": "",
        "DestTerminalFaxNo": "",
        "DestTerminalFreePhone": "",
        "DestTerminalName": "",
        "DestTerminalPhoneNo": "",
        "DestTerminalState": "",
        "DestTerminalZip": "",
        "DestTerminalZipCode": "",
        "Discount": 0,
        "DiscountID": 0,
        "DiscountRate": 0,
        "EquipmentCharges": null,
        "Equipments": null,
        "ExcludeReason": "",
        "FreightCost": 0,
        "FuelCost": 0,
        "FuelRate": 0,
        "GrossAmount": 0,
        "IsClientGainShare": false,
        "IsExcluded": true,
        "IsMinimumApplied": false,
        "IsVendorPortalRate": false,
        "LaneID": 1601593,
        "LaneName": "DAYTON - GUA PM - US-US - BLANKET API",
        "LaneWiseMiles": 1230,
        "MaxHeightShipmentLimit": "Max Height :12 Feet",
        "MaxLenghtShipmentLimit": "Max Length :15 linear Feet",
        "Miles": 1230,
        "MinAmount": 0,
        "ModeType": null,
        "NewInsuranceCost": 1000,
        "OldInsuranceCost": 500,
        "OriginTerminalAddress1": "",
        "OriginTerminalAddress2": "",
        "OriginTerminalCity": "",
        "OriginTerminalCode": "",
        "OriginTerminalContactName": "",
        "OriginTerminalContactTitle": "",
        "OriginTerminalEmail": "",
        "OriginTerminalFaxNo": "",
        "OriginTerminalFreePhone": "",
        "OriginTerminalName": "",
        "OriginTerminalPhoneNo": "",
        "OriginTerminalState": "",
        "OriginTerminalZip": "",
        "OriginTerminalZipCode": "",
        "PaymentType": "3rd Party Prepaid",
        "Products": [
          {
            "FAKClass": 0,
            "HazMat": false,
            "Height": 48,
            "Length": 48,
            "NmfcNumber": null,
            "PackageType": null,
            "PackageTypeID": null,
            "Pallets": 0,
            "Pieces": 1,
            "ProductClass": 50,
            "ProductCost": 0,
            "ProductDescription": null,
            "RateBase": 0,
            "Stackable": false,
            "Weight": 1000,
            "Width": 48
          }
        ],
        "ProfileID": 11868,
        "QuoteNumber": "",
        "RateType": "CarrierRateService",
        "RatingMarkUp": null,
        "RatingResultId": 57060348,
        "ReferenceNo": 8,
        "Remarks": "At least one of the points must be a direct serviced point of Dayton Freight Lines. Please call customer service at 800.860.5102 or your local service center.\r\nThe freight terms selected is prepaid and the shipper is a non-direct point, please either change the selected terms or call the Dayton Freight Pricing department at 800.860.5102",
        "SAASQuoteNumber": 61359355,
        "SaasBrokerCarrierCode": null,
        "SaasBrokerCarrierName": null,
        "SaasServiceLevelCode": "EXP",
        "ServiceLevel": "Guranteed PM",
        "ServiceLevelCode": null,
        "ShowTrueCost": false,
        "StatusCode": 0,
        "TariffName": null,
        "TotalAccCost": 0,
        "TotalAccCostWithOutTrueCost": 0,
        "TotalCost": 0,
        "TotalCostWithCustCostWithOutTrueCost": 0,
        "TotalCostWithOutTrueCost": 0,
        "TotalShipmentCostWithCustomerCost": 0,
        "TransitTime": "9",
        "UsedRatingFuel": {
          "EffectiveFrom": "/Date(662706000000-0500)/",
          "EffectiveTo": "/Date(662706000000-0500)/",
          "FuelLevel": null,
          "FuelRate": 0,
          "FuelRateType": "0",
          "MaxRate": 0,
          "Message": "",
          "MinRate": 0
        },
        "UsedRatingWeeklyFuel": null,
        "ZoneAreaID": 0,
        "ZoneID": 0,
        "ZoneRateID": 0
      },
      {
        "Accessorials": [],
        "ApiCallDuration": "00:00:00",
        "BenchMarkCost": null,
        "CarrierConnectRequestResponseString": null,
        "CarrierCost": 0,
        "CarrierCostWithOutTrueCost": 0,
        "CarrierID": "UPGF",
        "CarrierName": "UPS FREIGHT",
        "CarrierType": "Direct",
        "CarrierTypeID": 2,
        "CostWithCustomerPercentage": 0,
        "CostWithCustomerPercentageWithOutTrueCost": 0,
        "CustomerCost": 0,
        "DeficitCharge": 0,
        "DeficitWeight": 0,
        "DestTerminalAddress1": "1311 W 15TH ST",
        "DestTerminalAddress2": "-",
        "DestTerminalCity": "RIVIERA BEACH",
        "DestTerminalCode": "WPB",
        "DestTerminalContactName": "-",
        "DestTerminalContactTitle": "SERVICE CENTER MANAGER",
        "DestTerminalEmail": "-",
        "DestTerminalFaxNo": "561-863-8844",
        "DestTerminalFreePhone": "000-000-0000",
        "DestTerminalName": "WEST PALM BEACH",
        "DestTerminalPhoneNo": "561-863-2900",
        "DestTerminalState": "FL",
        "DestTerminalZip": "33404",
        "DestTerminalZipCode": "33404",
        "Discount": 0,
        "DiscountID": 0,
        "DiscountRate": 0,
        "EquipmentCharges": null,
        "Equipments": null,
        "ExcludeReason": "",
        "FreightCost": 0,
        "FuelCost": 0,
        "FuelRate": 0,
        "GrossAmount": 0,
        "IsClientGainShare": false,
        "IsExcluded": true,
        "IsMinimumApplied": false,
        "IsVendorPortalRate": false,
        "LaneID": 576291,
        "LaneName": "UPGF - STD - US-US - BLANKET API 91D",
        "LaneWiseMiles": 1230,
        "MaxHeightShipmentLimit": "Max Height :8 Feet",
        "MaxLenghtShipmentLimit": "Max Length :25 linear Feet",
        "Miles": 1230,
        "MinAmount": 0,
        "ModeType": null,
        "NewInsuranceCost": 1000,
        "OldInsuranceCost": 1000,
        "OriginTerminalAddress1": "3275 MILLER PARK S",
        "OriginTerminalAddress2": "-",
        "OriginTerminalCity": "GARLAND",
        "OriginTerminalCode": "GAR",
        "OriginTerminalContactName": "-",
        "OriginTerminalContactTitle": "SERVICE CENTER MANAGER",
        "OriginTerminalEmail": "-",
        "OriginTerminalFaxNo": "972-487-0114",
        "OriginTerminalFreePhone": "000-000-0000",
        "OriginTerminalName": "GARLAND",
        "OriginTerminalPhoneNo": "972-487-8267",
        "OriginTerminalState": "TX",
        "OriginTerminalZip": "75042",
        "OriginTerminalZipCode": "75042",
        "PaymentType": "3rd Party",
        "Products": [
          {
            "FAKClass": 0,
            "HazMat": false,
            "Height": 48,
            "Length": 48,
            "NmfcNumber": null,
            "PackageType": null,
            "PackageTypeID": null,
            "Pallets": 0,
            "Pieces": 1,
            "ProductClass": 50,
            "ProductCost": 0,
            "ProductDescription": null,
            "RateBase": 0,
            "Stackable": false,
            "Weight": 1000,
            "Width": 48
          }
        ],
        "ProfileID": 11868,
        "QuoteNumber": "",
        "RateType": "CarrierRateService",
        "RatingMarkUp": null,
        "RatingResultId": 57060346,
        "ReferenceNo": 3,
        "Remarks": "Service Call;Hard9360660Shipper has density pricing. Handling unit dimension required.",
        "SAASQuoteNumber": 61359355,
        "SaasBrokerCarrierCode": null,
        "SaasBrokerCarrierName": null,
        "SaasServiceLevelCode": "STD",
        "ServiceLevel": "Standard",
        "ServiceLevelCode": null,
        "ShowTrueCost": false,
        "StatusCode": 0,
        "TariffName": null,
        "TotalAccCost": 0,
        "TotalAccCostWithOutTrueCost": 0,
        "TotalCost": 0,
        "TotalCostWithCustCostWithOutTrueCost": 0,
        "TotalCostWithOutTrueCost": 0,
        "TotalShipmentCostWithCustomerCost": 0,
        "TransitTime": "3",
        "UsedRatingFuel": {
          "EffectiveFrom": "/Date(662706000000-0500)/",
          "EffectiveTo": "/Date(662706000000-0500)/",
          "FuelLevel": null,
          "FuelRate": 0,
          "FuelRateType": "0",
          "MaxRate": 0,
          "Message": "",
          "MinRate": 0
        },
        "UsedRatingWeeklyFuel": null,
        "ZoneAreaID": 0,
        "ZoneID": 0,
        "ZoneRateID": 0
      },
      {
        "Accessorials": [],
        "ApiCallDuration": "00:00:00",
        "BenchMarkCost": null,
        "CarrierConnectRequestResponseString": null,
        "CarrierCost": 0,
        "CarrierCostWithOutTrueCost": 0,
        "CarrierID": "UPGF",
        "CarrierName": "UPS FREIGHT",
        "CarrierType": "Direct",
        "CarrierTypeID": 2,
        "CostWithCustomerPercentage": 0,
        "CostWithCustomerPercentageWithOutTrueCost": 0,
        "CustomerCost": 0,
        "DeficitCharge": 0,
        "DeficitWeight": 0,
        "DestTerminalAddress1": "1311 W 15TH ST",
        "DestTerminalAddress2": "-",
        "DestTerminalCity": "RIVIERA BEACH",
        "DestTerminalCode": "WPB",
        "DestTerminalContactName": "-",
        "DestTerminalContactTitle": "SERVICE CENTER MANAGER",
        "DestTerminalEmail": "-",
        "DestTerminalFaxNo": "561-863-8844",
        "DestTerminalFreePhone": "000-000-0000",
        "DestTerminalName": "WEST PALM BEACH",
        "DestTerminalPhoneNo": "561-863-2900",
        "DestTerminalState": "FL",
        "DestTerminalZip": "33404",
        "DestTerminalZipCode": "33404",
        "Discount": 0,
        "DiscountID": 0,
        "DiscountRate": 0,
        "EquipmentCharges": null,
        "Equipments": null,
        "ExcludeReason": "",
        "FreightCost": 0,
        "FuelCost": 0,
        "FuelRate": 0,
        "GrossAmount": 0,
        "IsClientGainShare": false,
        "IsExcluded": true,
        "IsMinimumApplied": false,
        "IsVendorPortalRate": false,
        "LaneID": 576290,
        "LaneName": "UPGF - STD - US-US - BLANKET API 8D3",
        "LaneWiseMiles": 1230,
        "MaxHeightShipmentLimit": "Max Height :8 Feet",
        "MaxLenghtShipmentLimit": "Max Length :25 linear Feet",
        "Miles": 1230,
        "MinAmount": 0,
        "ModeType": null,
        "NewInsuranceCost": 1000,
        "OldInsuranceCost": 1000,
        "OriginTerminalAddress1": "3275 MILLER PARK S",
        "OriginTerminalAddress2": "-",
        "OriginTerminalCity": "GARLAND",
        "OriginTerminalCode": "GAR",
        "OriginTerminalContactName": "-",
        "OriginTerminalContactTitle": "SERVICE CENTER MANAGER",
        "OriginTerminalEmail": "-",
        "OriginTerminalFaxNo": "972-487-0114",
        "OriginTerminalFreePhone": "000-000-0000",
        "OriginTerminalName": "GARLAND",
        "OriginTerminalPhoneNo": "972-487-8267",
        "OriginTerminalState": "TX",
        "OriginTerminalZip": "75042",
        "OriginTerminalZipCode": "75042",
        "PaymentType": "3rd Party",
        "Products": [
          {
            "FAKClass": 0,
            "HazMat": false,
            "Height": 48,
            "Length": 48,
            "NmfcNumber": null,
            "PackageType": null,
            "PackageTypeID": null,
            "Pallets": 0,
            "Pieces": 1,
            "ProductClass": 50,
            "ProductCost": 0,
            "ProductDescription": null,
            "RateBase": 0,
            "Stackable": false,
            "Weight": 1000,
            "Width": 48
          }
        ],
        "ProfileID": 11868,
        "QuoteNumber": "",
        "RateType": "CarrierRateService",
        "RatingMarkUp": null,
        "RatingResultId": 57060347,
        "ReferenceNo": 4,
        "Remarks": "Service Call;Hard9360660Shipper has density pricing. Handling unit dimension required.",
        "SAASQuoteNumber": 61359355,
        "SaasBrokerCarrierCode": null,
        "SaasBrokerCarrierName": null,
        "SaasServiceLevelCode": "STD",
        "ServiceLevel": "Standard",
        "ServiceLevelCode": null,
        "ShowTrueCost": false,
        "StatusCode": 0,
        "TariffName": null,
        "TotalAccCost": 0,
        "TotalAccCostWithOutTrueCost": 0,
        "TotalCost": 0,
        "TotalCostWithCustCostWithOutTrueCost": 0,
        "TotalCostWithOutTrueCost": 0,
        "TotalShipmentCostWithCustomerCost": 0,
        "TransitTime": "3",
        "UsedRatingFuel": {
          "EffectiveFrom": "/Date(662706000000-0500)/",
          "EffectiveTo": "/Date(662706000000-0500)/",
          "FuelLevel": null,
          "FuelRate": 0,
          "FuelRateType": "0",
          "MaxRate": 0,
          "Message": "",
          "MinRate": 0
        },
        "UsedRatingWeeklyFuel": null,
        "ZoneAreaID": 0,
        "ZoneID": 0,
        "ZoneRateID": 0
      },
      {
        "Accessorials": [],
        "ApiCallDuration": "00:00:00",
        "BenchMarkCost": null,
        "CarrierConnectRequestResponseString": null,
        "CarrierCost": 0,
        "CarrierCostWithOutTrueCost": 0,
        "CarrierID": "DAFG",
        "CarrierName": "DAYTON FREIGHT LINES          ",
        "CarrierType": "",
        "CarrierTypeID": 2,
        "CostWithCustomerPercentage": 0,
        "CostWithCustomerPercentageWithOutTrueCost": 0,
        "CustomerCost": 0,
        "DeficitCharge": 0,
        "DeficitWeight": 0,
        "DestTerminalAddress1": "",
        "DestTerminalAddress2": "",
        "DestTerminalCity": "",
        "DestTerminalCode": "",
        "DestTerminalContactName": "",
        "DestTerminalContactTitle": "",
        "DestTerminalEmail": "",
        "DestTerminalFaxNo": "",
        "DestTerminalFreePhone": "",
        "DestTerminalName": "",
        "DestTerminalPhoneNo": "",
        "DestTerminalState": "",
        "DestTerminalZip": "",
        "DestTerminalZipCode": "",
        "Discount": 0,
        "DiscountID": 0,
        "DiscountRate": 0,
        "EquipmentCharges": null,
        "Equipments": null,
        "ExcludeReason": "",
        "FreightCost": 0,
        "FuelCost": 0,
        "FuelRate": 0,
        "GrossAmount": 0,
        "IsClientGainShare": false,
        "IsExcluded": true,
        "IsMinimumApplied": false,
        "IsVendorPortalRate": false,
        "LaneID": 712369,
        "LaneName": "DAYTON - GUA AM - US-US - BLANKET API",
        "LaneWiseMiles": 1230,
        "MaxHeightShipmentLimit": "Max Height :12 Feet",
        "MaxLenghtShipmentLimit": "Max Length :15 linear Feet",
        "Miles": 1230,
        "MinAmount": 0,
        "ModeType": null,
        "NewInsuranceCost": 1000,
        "OldInsuranceCost": 500,
        "OriginTerminalAddress1": "",
        "OriginTerminalAddress2": "",
        "OriginTerminalCity": "",
        "OriginTerminalCode": "",
        "OriginTerminalContactName": "",
        "OriginTerminalContactTitle": "",
        "OriginTerminalEmail": "",
        "OriginTerminalFaxNo": "",
        "OriginTerminalFreePhone": "",
        "OriginTerminalName": "",
        "OriginTerminalPhoneNo": "",
        "OriginTerminalState": "",
        "OriginTerminalZip": "",
        "OriginTerminalZipCode": "",
        "PaymentType": "3rd Party Prepaid",
        "Products": [
          {
            "FAKClass": 0,
            "HazMat": false,
            "Height": 48,
            "Length": 48,
            "NmfcNumber": null,
            "PackageType": null,
            "PackageTypeID": null,
            "Pallets": 0,
            "Pieces": 1,
            "ProductClass": 50,
            "ProductCost": 0,
            "ProductDescription": null,
            "RateBase": 0,
            "Stackable": false,
            "Weight": 1000,
            "Width": 48
          }
        ],
        "ProfileID": 11868,
        "QuoteNumber": "",
        "RateType": "CarrierRateService",
        "RatingMarkUp": null,
        "RatingResultId": 57060349,
        "ReferenceNo": 6,
        "Remarks": "At least one of the points must be a direct serviced point of Dayton Freight Lines. Please call customer service at 800.860.5102 or your local service center.\r\nThe freight terms selected is prepaid and the shipper is a non-direct point, please either change the selected terms or call the Dayton Freight Pricing department at 800.860.5102",
        "SAASQuoteNumber": 61359355,
        "SaasBrokerCarrierCode": null,
        "SaasBrokerCarrierName": null,
        "SaasServiceLevelCode": "EXA",
        "ServiceLevel": "Guranteed AM",
        "ServiceLevelCode": null,
        "ShowTrueCost": false,
        "StatusCode": 0,
        "TariffName": null,
        "TotalAccCost": 0,
        "TotalAccCostWithOutTrueCost": 0,
        "TotalCost": 0,
        "TotalCostWithCustCostWithOutTrueCost": 0,
        "TotalCostWithOutTrueCost": 0,
        "TotalShipmentCostWithCustomerCost": 0,
        "TransitTime": "9",
        "UsedRatingFuel": {
          "EffectiveFrom": "/Date(662706000000-0500)/",
          "EffectiveTo": "/Date(662706000000-0500)/",
          "FuelLevel": null,
          "FuelRate": 0,
          "FuelRateType": "0",
          "MaxRate": 0,
          "Message": "",
          "MinRate": 0
        },
        "UsedRatingWeeklyFuel": null,
        "ZoneAreaID": 0,
        "ZoneID": 0,
        "ZoneRateID": 0
      },
      {
        "Accessorials": [],
        "ApiCallDuration": "00:00:00.1562501",
        "BenchMarkCost": null,
        "CarrierConnectRequestResponseString": null,
        "CarrierCost": 0,
        "CarrierCostWithOutTrueCost": 0,
        "CarrierID": "RETL",
        "CarrierName": "USF REDDAWAY",
        "CarrierType": "",
        "CarrierTypeID": 2,
        "CostWithCustomerPercentage": 0,
        "CostWithCustomerPercentageWithOutTrueCost": 0,
        "CustomerCost": 0,
        "DeficitCharge": 0,
        "DeficitWeight": 0,
        "DestTerminalAddress1": "",
        "DestTerminalAddress2": "",
        "DestTerminalCity": "",
        "DestTerminalCode": "",
        "DestTerminalContactName": "",
        "DestTerminalContactTitle": "",
        "DestTerminalEmail": "",
        "DestTerminalFaxNo": "",
        "DestTerminalFreePhone": "",
        "DestTerminalName": "",
        "DestTerminalPhoneNo": "",
        "DestTerminalState": "",
        "DestTerminalZip": "",
        "DestTerminalZipCode": "",
        "Discount": 0,
        "DiscountID": 0,
        "DiscountRate": 0,
        "EquipmentCharges": null,
        "Equipments": null,
        "ExcludeReason": "",
        "FreightCost": 0,
        "FuelCost": 0,
        "FuelRate": 0,
        "GrossAmount": 0,
        "IsClientGainShare": false,
        "IsExcluded": true,
        "IsMinimumApplied": false,
        "IsVendorPortalRate": false,
        "LaneID": 697741,
        "LaneName": "RETL - GUA PM - US-US - BLANKET API",
        "LaneWiseMiles": 1230,
        "MaxHeightShipmentLimit": "Max Height :8 Feet",
        "MaxLenghtShipmentLimit": "Max Length :8 linear Feet",
        "Miles": 1230,
        "MinAmount": 0,
        "ModeType": null,
        "NewInsuranceCost": 2000,
        "OldInsuranceCost": 500,
        "OriginTerminalAddress1": "",
        "OriginTerminalAddress2": "",
        "OriginTerminalCity": "",
        "OriginTerminalCode": "",
        "OriginTerminalContactName": "",
        "OriginTerminalContactTitle": "",
        "OriginTerminalEmail": "",
        "OriginTerminalFaxNo": "",
        "OriginTerminalFreePhone": "",
        "OriginTerminalName": "",
        "OriginTerminalPhoneNo": "",
        "OriginTerminalState": "",
        "OriginTerminalZip": "",
        "OriginTerminalZipCode": "",
        "PaymentType": "Prepaid",
        "Products": [
          {
            "FAKClass": 0,
            "HazMat": false,
            "Height": 48,
            "Length": 48,
            "NmfcNumber": null,
            "PackageType": null,
            "PackageTypeID": null,
            "Pallets": 0,
            "Pieces": 1,
            "ProductClass": 50,
            "ProductCost": 0,
            "ProductDescription": null,
            "RateBase": 0,
            "Stackable": false,
            "Weight": 1000,
            "Width": 48
          }
        ],
        "ProfileID": 11868,
        "QuoteNumber": "",
        "RateType": "CarrierRateService",
        "RatingMarkUp": null,
        "RatingResultId": 57060350,
        "ReferenceNo": 13,
        "Remarks": "Non service lane, Please call 888-420-8960.",
        "SAASQuoteNumber": 61359355,
        "SaasBrokerCarrierCode": null,
        "SaasBrokerCarrierName": null,
        "SaasServiceLevelCode": "EXP",
        "ServiceLevel": "Guranteed PM",
        "ServiceLevelCode": null,
        "ShowTrueCost": false,
        "StatusCode": 0,
        "TariffName": null,
        "TotalAccCost": 0,
        "TotalAccCostWithOutTrueCost": 0,
        "TotalCost": 0,
        "TotalCostWithCustCostWithOutTrueCost": 0,
        "TotalCostWithOutTrueCost": 0,
        "TotalShipmentCostWithCustomerCost": 0,
        "TransitTime": "9",
        "UsedRatingFuel": {
          "EffectiveFrom": "/Date(662706000000-0500)/",
          "EffectiveTo": "/Date(662706000000-0500)/",
          "FuelLevel": null,
          "FuelRate": 0,
          "FuelRateType": "0",
          "MaxRate": 0,
          "Message": "",
          "MinRate": 0
        },
        "UsedRatingWeeklyFuel": null,
        "ZoneAreaID": 0,
        "ZoneID": 0,
        "ZoneRateID": 0
      },
      {
        "Accessorials": [],
        "ApiCallDuration": "00:00:00.1718842",
        "BenchMarkCost": null,
        "CarrierConnectRequestResponseString": null,
        "CarrierCost": 0,
        "CarrierCostWithOutTrueCost": 0,
        "CarrierID": "RETL",
        "CarrierName": "USF REDDAWAY",
        "CarrierType": "",
        "CarrierTypeID": 2,
        "CostWithCustomerPercentage": 0,
        "CostWithCustomerPercentageWithOutTrueCost": 0,
        "CustomerCost": 0,
        "DeficitCharge": 0,
        "DeficitWeight": 0,
        "DestTerminalAddress1": "",
        "DestTerminalAddress2": "",
        "DestTerminalCity": "",
        "DestTerminalCode": "",
        "DestTerminalContactName": "",
        "DestTerminalContactTitle": "",
        "DestTerminalEmail": "",
        "DestTerminalFaxNo": "",
        "DestTerminalFreePhone": "",
        "DestTerminalName": "",
        "DestTerminalPhoneNo": "",
        "DestTerminalState": "",
        "DestTerminalZip": "",
        "DestTerminalZipCode": "",
        "Discount": 0,
        "DiscountID": 0,
        "DiscountRate": 0,
        "EquipmentCharges": null,
        "Equipments": null,
        "ExcludeReason": "",
        "FreightCost": 0,
        "FuelCost": 0,
        "FuelRate": 0,
        "GrossAmount": 0,
        "IsClientGainShare": false,
        "IsExcluded": true,
        "IsMinimumApplied": false,
        "IsVendorPortalRate": false,
        "LaneID": 697740,
        "LaneName": "RETL - GUA AM - US-US - BLANKET API",
        "LaneWiseMiles": 1230,
        "MaxHeightShipmentLimit": "Max Height :8 Feet",
        "MaxLenghtShipmentLimit": "Max Length :8 linear Feet",
        "Miles": 1230,
        "MinAmount": 0,
        "ModeType": null,
        "NewInsuranceCost": 2000,
        "OldInsuranceCost": 500,
        "OriginTerminalAddress1": "",
        "OriginTerminalAddress2": "",
        "OriginTerminalCity": "",
        "OriginTerminalCode": "",
        "OriginTerminalContactName": "",
        "OriginTerminalContactTitle": "",
        "OriginTerminalEmail": "",
        "OriginTerminalFaxNo": "",
        "OriginTerminalFreePhone": "",
        "OriginTerminalName": "",
        "OriginTerminalPhoneNo": "",
        "OriginTerminalState": "",
        "OriginTerminalZip": "",
        "OriginTerminalZipCode": "",
        "PaymentType": "Prepaid",
        "Products": [
          {
            "FAKClass": 0,
            "HazMat": false,
            "Height": 48,
            "Length": 48,
            "NmfcNumber": null,
            "PackageType": null,
            "PackageTypeID": null,
            "Pallets": 0,
            "Pieces": 1,
            "ProductClass": 50,
            "ProductCost": 0,
            "ProductDescription": null,
            "RateBase": 0,
            "Stackable": false,
            "Weight": 1000,
            "Width": 48
          }
        ],
        "ProfileID": 11868,
        "QuoteNumber": "",
        "RateType": "CarrierRateService",
        "RatingMarkUp": null,
        "RatingResultId": 57060351,
        "ReferenceNo": 12,
        "Remarks": "Non service lane, Please call 888-420-8960.",
        "SAASQuoteNumber": 61359355,
        "SaasBrokerCarrierCode": null,
        "SaasBrokerCarrierName": null,
        "SaasServiceLevelCode": "EXA",
        "ServiceLevel": "Guranteed AM",
        "ServiceLevelCode": null,
        "ShowTrueCost": false,
        "StatusCode": 0,
        "TariffName": null,
        "TotalAccCost": 0,
        "TotalAccCostWithOutTrueCost": 0,
        "TotalCost": 0,
        "TotalCostWithCustCostWithOutTrueCost": 0,
        "TotalCostWithOutTrueCost": 0,
        "TotalShipmentCostWithCustomerCost": 0,
        "TransitTime": "9",
        "UsedRatingFuel": {
          "EffectiveFrom": "/Date(662706000000-0500)/",
          "EffectiveTo": "/Date(662706000000-0500)/",
          "FuelLevel": null,
          "FuelRate": 0,
          "FuelRateType": "0",
          "MaxRate": 0,
          "Message": "",
          "MinRate": 0
        },
        "UsedRatingWeeklyFuel": null,
        "ZoneAreaID": 0,
        "ZoneID": 0,
        "ZoneRateID": 0
      },
      {
        "Accessorials": [
          {
            "AccessorialCharge": 14.91,
            "AccessorialCode": "HND",
            "AccessorialDescription": "HND",
            "AccessorialID": -1,
            "AccessorialLevel": null,
            "AccessorialRate": 0,
            "AccessorialType": 0,
            "IsIncluded": false,
            "IsNotRated": false,
            "IsSystem": false,
            "Message": null,
            "ShowTrueCost": true,
            "WeightFrom": 0,
            "WeightTo": 0
          }
        ],
        "ApiCallDuration": "00:00:03.1563090",
        "BenchMarkCost": null,
        "CarrierConnectRequestResponseString": null,
        "CarrierCost": 154.16,
        "CarrierCostWithOutTrueCost": 154.16,
        "CarrierID": "RDFS",
        "CarrierName": "ROADRUNNER TRANSPORTATION",
        "CarrierType": "Direct",
        "CarrierTypeID": 2,
        "CostWithCustomerPercentage": 0,
        "CostWithCustomerPercentageWithOutTrueCost": 0,
        "CustomerCost": 0,
        "DeficitCharge": 0,
        "DeficitWeight": 0,
        "DestTerminalAddress1": "11401 NW 134TH STREET",
        "DestTerminalAddress2": "-",
        "DestTerminalCity": "MEDLEY",
        "DestTerminalCode": "MIA",
        "DestTerminalContactName": "-",
        "DestTerminalContactTitle": "-",
        "DestTerminalEmail": "-",
        "DestTerminalFaxNo": "000-000-0000",
        "DestTerminalFreePhone": "414-769-4603",
        "DestTerminalName": "ROADRUNNER TRANSPORTATION SERVICES INC",
        "DestTerminalPhoneNo": "855-216-3171",
        "DestTerminalState": "FL",
        "DestTerminalZip": "33178",
        "DestTerminalZipCode": "33178",
        "Discount": 395.82,
        "DiscountID": 0,
        "DiscountRate": 0,
        "EquipmentCharges": null,
        "Equipments": null,
        "ExcludeReason": "",
        "FreightCost": 129.53,
        "FuelCost": 9.72,
        "FuelRate": 0,
        "GrossAmount": 525.35,
        "IsClientGainShare": false,
        "IsExcluded": true,
        "IsMinimumApplied": false,
        "IsVendorPortalRate": false,
        "LaneID": 690625,
        "LaneName": "RDFS - STD - USA-USA - BLANKET API",
        "LaneWiseMiles": 1230,
        "MaxHeightShipmentLimit": "Max Height :8 Feet",
        "MaxLenghtShipmentLimit": "Max Length :13 linear Feet",
        "Miles": 1230,
        "MinAmount": 0,
        "ModeType": null,
        "NewInsuranceCost": 1000,
        "OldInsuranceCost": 100,
        "OriginTerminalAddress1": "210 W TRINITY BLVD",
        "OriginTerminalAddress2": "-",
        "OriginTerminalCity": "GRAND PRAIRIE",
        "OriginTerminalCode": "DLS",
        "OriginTerminalContactName": "-",
        "OriginTerminalContactTitle": "-",
        "OriginTerminalEmail": "-",
        "OriginTerminalFaxNo": "000-000-0000",
        "OriginTerminalFreePhone": "972-510-0216",
        "OriginTerminalName": "ROADRUNNER TRANSPORTATION SERVICES INC",
        "OriginTerminalPhoneNo": "800-697-7337",
        "OriginTerminalState": "TX",
        "OriginTerminalZip": "75050",
        "OriginTerminalZipCode": "75050",
        "PaymentType": "Prepaid",
        "Products": [
          {
            "FAKClass": 0,
            "HazMat": false,
            "Height": 48,
            "Length": 48,
            "NmfcNumber": null,
            "PackageType": null,
            "PackageTypeID": null,
            "Pallets": 0,
            "Pieces": 1,
            "ProductClass": 50,
            "ProductCost": 0,
            "ProductDescription": null,
            "RateBase": 0,
            "Stackable": false,
            "Weight": 1000,
            "Width": 48
          }
        ],
        "ProfileID": 11868,
        "QuoteNumber": "4140469",
        "RateType": "CarrierRateService",
        "RatingMarkUp": null,
        "RatingResultId": 57060376,
        "ReferenceNo": 34,
        "Remarks": null,
        "SAASQuoteNumber": 61359355,
        "SaasBrokerCarrierCode": null,
        "SaasBrokerCarrierName": null,
        "SaasServiceLevelCode": "STD",
        "ServiceLevel": "Standard",
        "ServiceLevelCode": null,
        "ShowTrueCost": false,
        "StatusCode": 1,
        "TariffName": null,
        "TotalAccCost": 14.91,
        "TotalAccCostWithOutTrueCost": 14.91,
        "TotalCost": 154.16,
        "TotalCostWithCustCostWithOutTrueCost": 154.16,
        "TotalCostWithOutTrueCost": 154.16,
        "TotalShipmentCostWithCustomerCost": 154.16,
        "TransitTime": "4",
        "UsedRatingFuel": {
          "EffectiveFrom": "/Date(662706000000-0500)/",
          "EffectiveTo": "/Date(662706000000-0500)/",
          "FuelLevel": null,
          "FuelRate": 0,
          "FuelRateType": "0",
          "MaxRate": 0,
          "Message": "",
          "MinRate": 0
        },
        "UsedRatingWeeklyFuel": null,
        "ZoneAreaID": 0,
        "ZoneID": 0,
        "ZoneRateID": 0
      },
      {
        "Accessorials": [],
        "ApiCallDuration": "00:00:01.0937455",
        "BenchMarkCost": null,
        "CarrierConnectRequestResponseString": null,
        "CarrierCost": 168.87,
        "CarrierCostWithOutTrueCost": 168.87,
        "CarrierID": "SEFL",
        "CarrierName": "SOUTHEASTERN FREIGHT LINES",
        "CarrierType": "Direct",
        "CarrierTypeID": 2,
        "CostWithCustomerPercentage": 0,
        "CostWithCustomerPercentageWithOutTrueCost": 0,
        "CustomerCost": 0,
        "DeficitCharge": 0,
        "DeficitWeight": 0,
        "DestTerminalAddress1": "201 AVENUE P",
        "DestTerminalAddress2": "-",
        "DestTerminalCity": "RIVIERA BEACH",
        "DestTerminalCode": "WPB",
        "DestTerminalContactName": "NICK CRAWFORD",
        "DestTerminalContactTitle": "TERMINAL MANAGER",
        "DestTerminalEmail": "nicholas.crawford@sefl.com",
        "DestTerminalFaxNo": "561-848-2632",
        "DestTerminalFreePhone": "800-282-7335",
        "DestTerminalName": "WEST PALM BEACH",
        "DestTerminalPhoneNo": "561-881-9980",
        "DestTerminalState": "FL",
        "DestTerminalZip": "33404",
        "DestTerminalZipCode": "33404",
        "Discount": 99.05,
        "DiscountID": 0,
        "DiscountRate": 0,
        "EquipmentCharges": null,
        "Equipments": null,
        "ExcludeReason": "",
        "FreightCost": 146.46,
        "FuelCost": 22.41,
        "FuelRate": 0,
        "GrossAmount": 245.51,
        "IsClientGainShare": false,
        "IsExcluded": true,
        "IsMinimumApplied": false,
        "IsVendorPortalRate": false,
        "LaneID": 352895,
        "LaneName": "SEFL - STD - US-US - BLANKET API",
        "LaneWiseMiles": 1230,
        "MaxHeightShipmentLimit": "Max Height :8 Feet",
        "MaxLenghtShipmentLimit": "Max Length :12 linear Feet",
        "Miles": 1230,
        "MinAmount": 0,
        "ModeType": null,
        "NewInsuranceCost": 990,
        "OldInsuranceCost": 100,
        "OriginTerminalAddress1": "3301 WEST MILLER ROAD",
        "OriginTerminalAddress2": "-",
        "OriginTerminalCity": "GARLAND",
        "OriginTerminalCode": "GAR",
        "OriginTerminalContactName": "KEVIN OWENS",
        "OriginTerminalContactTitle": "TERMINAL MANAGER",
        "OriginTerminalEmail": "KEVIN.M.OWENS@SEFL.COM",
        "OriginTerminalFaxNo": "972-271-0804",
        "OriginTerminalFreePhone": "855-782-7335",
        "OriginTerminalName": "GARLAND",
        "OriginTerminalPhoneNo": "972-271-0770",
        "OriginTerminalState": "TX",
        "OriginTerminalZip": "75041",
        "OriginTerminalZipCode": "75041",
        "PaymentType": "Prepaid",
        "Products": [
          {
            "FAKClass": 0,
            "HazMat": false,
            "Height": 48,
            "Length": 48,
            "NmfcNumber": null,
            "PackageType": null,
            "PackageTypeID": null,
            "Pallets": 0,
            "Pieces": 1,
            "ProductClass": 50,
            "ProductCost": 0,
            "ProductDescription": null,
            "RateBase": 0,
            "Stackable": false,
            "Weight": 1000,
            "Width": 48
          }
        ],
        "ProfileID": 11868,
        "QuoteNumber": "CXFTC97C1",
        "RateType": "CarrierRateService",
        "RatingMarkUp": null,
        "RatingResultId": 57060366,
        "ReferenceNo": 28,
        "Remarks": null,
        "SAASQuoteNumber": 61359355,
        "SaasBrokerCarrierCode": null,
        "SaasBrokerCarrierName": null,
        "SaasServiceLevelCode": "STD",
        "ServiceLevel": "Standard",
        "ServiceLevelCode": null,
        "ShowTrueCost": false,
        "StatusCode": 1,
        "TariffName": null,
        "TotalAccCost": 0,
        "TotalAccCostWithOutTrueCost": 0,
        "TotalCost": 168.87,
        "TotalCostWithCustCostWithOutTrueCost": 168.87,
        "TotalCostWithOutTrueCost": 168.87,
        "TotalShipmentCostWithCustomerCost": 168.87,
        "TransitTime": "2",
        "UsedRatingFuel": {
          "EffectiveFrom": "/Date(662706000000-0500)/",
          "EffectiveTo": "/Date(662706000000-0500)/",
          "FuelLevel": null,
          "FuelRate": 0,
          "FuelRateType": "0",
          "MaxRate": 0,
          "Message": "",
          "MinRate": 0
        },
        "UsedRatingWeeklyFuel": null,
        "ZoneAreaID": 0,
        "ZoneID": 0,
        "ZoneRateID": 0
      },
      {
        "Accessorials": [],
        "ApiCallDuration": "00:00:04.5781924",
        "BenchMarkCost": null,
        "CarrierConnectRequestResponseString": null,
        "CarrierCost": 185.36,
        "CarrierCostWithOutTrueCost": 185.36,
        "CarrierID": "AACT",
        "CarrierName": "AAA COOPER TRANSPORTATION",
        "CarrierType": "Direct",
        "CarrierTypeID": 2,
        "CostWithCustomerPercentage": 0,
        "CostWithCustomerPercentageWithOutTrueCost": 0,
        "CustomerCost": 0,
        "DeficitCharge": 0,
        "DeficitWeight": 0,
        "DestTerminalAddress1": "7511 COMMERCIAL CIRCLE",
        "DestTerminalAddress2": "-",
        "DestTerminalCity": "FORT PIERCE",
        "DestTerminalCode": "FPR",
        "DestTerminalContactName": "MARK BRADY",
        "DestTerminalContactTitle": "TERMINAL MANAGER",
        "DestTerminalEmail": "MARK.BRADY@AAACOOPER.COM",
        "DestTerminalFaxNo": "855-206-4853",
        "DestTerminalFreePhone": "800-252-0246",
        "DestTerminalName": "FORT PIERCE",
        "DestTerminalPhoneNo": "772-429-2797",
        "DestTerminalState": "FL",
        "DestTerminalZip": "34951",
        "DestTerminalZipCode": "34951",
        "Discount": 1638.62,
        "DiscountID": 0,
        "DiscountRate": 0,
        "EquipmentCharges": null,
        "Equipments": null,
        "ExcludeReason": "",
        "FreightCost": 155.24,
        "FuelCost": 30.12,
        "FuelRate": 0,
        "GrossAmount": 1793.86,
        "IsClientGainShare": false,
        "IsExcluded": true,
        "IsMinimumApplied": false,
        "IsVendorPortalRate": false,
        "LaneID": 1553538,
        "LaneName": "AACT - Blanket Pricing - STD - USA - USA",
        "LaneWiseMiles": 1230,
        "MaxHeightShipmentLimit": "Max Height :8 Feet",
        "MaxLenghtShipmentLimit": "Max Length :12 linear Feet",
        "Miles": 1230,
        "MinAmount": 0,
        "ModeType": null,
        "NewInsuranceCost": 990,
        "OldInsuranceCost": 100,
        "OriginTerminalAddress1": "311 WEST TRINITY BLVD",
        "OriginTerminalAddress2": "-",
        "OriginTerminalCity": "GRAND PRAIRIE",
        "OriginTerminalCode": "DAL",
        "OriginTerminalContactName": "JACOB BASS",
        "OriginTerminalContactTitle": "TERMINAL MANAGER",
        "OriginTerminalEmail": "JACOB.BASS@AAACOOPER.COM",
        "OriginTerminalFaxNo": "855-261-7682",
        "OriginTerminalFreePhone": "800-354-2465",
        "OriginTerminalName": "DALLAS",
        "OriginTerminalPhoneNo": "972-266-9045",
        "OriginTerminalState": "TX",
        "OriginTerminalZip": "75050",
        "OriginTerminalZipCode": "75050",
        "PaymentType": "Prepaid",
        "Products": [
          {
            "FAKClass": 0,
            "HazMat": false,
            "Height": 48,
            "Length": 48,
            "NmfcNumber": null,
            "PackageType": null,
            "PackageTypeID": null,
            "Pallets": 0,
            "Pieces": 1,
            "ProductClass": 50,
            "ProductCost": 0,
            "ProductDescription": null,
            "RateBase": 0,
            "Stackable": false,
            "Weight": 1000,
            "Width": 48
          }
        ],
        "ProfileID": 11868,
        "QuoteNumber": "006156500",
        "RateType": "CarrierRateService",
        "RatingMarkUp": null,
        "RatingResultId": 57060378,
        "ReferenceNo": 39,
        "Remarks": null,
        "SAASQuoteNumber": 61359355,
        "SaasBrokerCarrierCode": null,
        "SaasBrokerCarrierName": null,
        "SaasServiceLevelCode": "STD",
        "ServiceLevel": "Standard",
        "ServiceLevelCode": null,
        "ShowTrueCost": false,
        "StatusCode": 1,
        "TariffName": null,
        "TotalAccCost": 0,
        "TotalAccCostWithOutTrueCost": 0,
        "TotalCost": 185.36,
        "TotalCostWithCustCostWithOutTrueCost": 185.36,
        "TotalCostWithOutTrueCost": 185.36,
        "TotalShipmentCostWithCustomerCost": 185.36,
        "TransitTime": "3",
        "UsedRatingFuel": {
          "EffectiveFrom": "/Date(662706000000-0500)/",
          "EffectiveTo": "/Date(662706000000-0500)/",
          "FuelLevel": null,
          "FuelRate": 0,
          "FuelRateType": "0",
          "MaxRate": 0,
          "Message": "",
          "MinRate": 0
        },
        "UsedRatingWeeklyFuel": null,
        "ZoneAreaID": 0,
        "ZoneID": 0,
        "ZoneRateID": 0
      },
      {
        "Accessorials": [],
        "ApiCallDuration": "00:00:02.4844398",
        "BenchMarkCost": null,
        "CarrierConnectRequestResponseString": null,
        "CarrierCost": 185.53,
        "CarrierCostWithOutTrueCost": 185.53,
        "CarrierID": "YFSY",
        "CarrierName": "YRC FREIGHT",
        "CarrierType": "Direct",
        "CarrierTypeID": 2,
        "CostWithCustomerPercentage": 0,
        "CostWithCustomerPercentageWithOutTrueCost": 0,
        "CustomerCost": 0,
        "DeficitCharge": 0,
        "DeficitWeight": 0,
        "DestTerminalAddress1": "1400 SW 30TH AVE",
        "DestTerminalAddress2": "-",
        "DestTerminalCity": "BOYNTON BEACH",
        "DestTerminalCode": "757",
        "DestTerminalContactName": "DAVIS",
        "DestTerminalContactTitle": "-",
        "DestTerminalEmail": "-",
        "DestTerminalFaxNo": "000-000-0000",
        "DestTerminalFreePhone": "800-610-6500",
        "DestTerminalName": "WEST PALM BEACH",
        "DestTerminalPhoneNo": "561-735-0988",
        "DestTerminalState": "FL",
        "DestTerminalZip": "33426",
        "DestTerminalZipCode": "33426",
        "Discount": 1272.06,
        "DiscountID": 0,
        "DiscountRate": 0,
        "EquipmentCharges": null,
        "Equipments": null,
        "ExcludeReason": "",
        "FreightCost": 153.77,
        "FuelCost": 31.76,
        "FuelRate": 0,
        "GrossAmount": 1425.83,
        "IsClientGainShare": false,
        "IsExcluded": true,
        "IsMinimumApplied": false,
        "IsVendorPortalRate": false,
        "LaneID": 1639703,
        "LaneName": "YRC - STD - US-US - BLANKET API",
        "LaneWiseMiles": 1230,
        "MaxHeightShipmentLimit": "Max Height :8 Feet",
        "MaxLenghtShipmentLimit": "Max Length :11 linear Feet",
        "Miles": 1230,
        "MinAmount": 0,
        "ModeType": null,
        "NewInsuranceCost": 0,
        "OldInsuranceCost": 0,
        "OriginTerminalAddress1": "12340 E NORTHWEST HWY",
        "OriginTerminalAddress2": "-",
        "OriginTerminalCity": "DALLAS",
        "OriginTerminalCode": "508",
        "OriginTerminalContactName": "NOTT",
        "OriginTerminalContactTitle": "-",
        "OriginTerminalEmail": "-",
        "OriginTerminalFaxNo": "877-667-9425",
        "OriginTerminalFreePhone": "800-610-6500",
        "OriginTerminalName": "GARLAND",
        "OriginTerminalPhoneNo": "214-819-4578",
        "OriginTerminalState": "TX",
        "OriginTerminalZip": "75228",
        "OriginTerminalZipCode": "75228",
        "PaymentType": "Prepaid",
        "Products": [
          {
            "FAKClass": 50,
            "HazMat": false,
            "Height": 48,
            "Length": 48,
            "NmfcNumber": null,
            "PackageType": null,
            "PackageTypeID": null,
            "Pallets": 0,
            "Pieces": 1,
            "ProductClass": 50,
            "ProductCost": 0,
            "ProductDescription": null,
            "RateBase": 0,
            "Stackable": false,
            "Weight": 1000,
            "Width": 48
          }
        ],
        "ProfileID": 11868,
        "QuoteNumber": "",
        "RateType": "CarrierRateService",
        "RatingMarkUp": null,
        "RatingResultId": 57060373,
        "ReferenceNo": 33,
        "Remarks": null,
        "SAASQuoteNumber": 61359355,
        "SaasBrokerCarrierCode": null,
        "SaasBrokerCarrierName": null,
        "SaasServiceLevelCode": "STD",
        "ServiceLevel": "Standard",
        "ServiceLevelCode": null,
        "ShowTrueCost": false,
        "StatusCode": 1,
        "TariffName": null,
        "TotalAccCost": 0,
        "TotalAccCostWithOutTrueCost": 0,
        "TotalCost": 185.53,
        "TotalCostWithCustCostWithOutTrueCost": 185.53,
        "TotalCostWithOutTrueCost": 185.53,
        "TotalShipmentCostWithCustomerCost": 185.53,
        "TransitTime": "3",
        "UsedRatingFuel": {
          "EffectiveFrom": "/Date(662706000000-0500)/",
          "EffectiveTo": "/Date(662706000000-0500)/",
          "FuelLevel": null,
          "FuelRate": 0,
          "FuelRateType": "0",
          "MaxRate": 0,
          "Message": "",
          "MinRate": 0
        },
        "UsedRatingWeeklyFuel": null,
        "ZoneAreaID": 0,
        "ZoneID": 0,
        "ZoneRateID": 0
      },
      {
        "Accessorials": [],
        "ApiCallDuration": "00:00:02.1250387",
        "BenchMarkCost": null,
        "CarrierConnectRequestResponseString": null,
        "CarrierCost": 185.53,
        "CarrierCostWithOutTrueCost": 185.53,
        "CarrierID": "YFSY",
        "CarrierName": "YRC FREIGHT",
        "CarrierType": "Direct",
        "CarrierTypeID": 2,
        "CostWithCustomerPercentage": 0,
        "CostWithCustomerPercentageWithOutTrueCost": 0,
        "CustomerCost": 0,
        "DeficitCharge": 0,
        "DeficitWeight": 0,
        "DestTerminalAddress1": "1400 SW 30TH AVE",
        "DestTerminalAddress2": "-",
        "DestTerminalCity": "BOYNTON BEACH",
        "DestTerminalCode": "757",
        "DestTerminalContactName": "DAVIS",
        "DestTerminalContactTitle": "-",
        "DestTerminalEmail": "-",
        "DestTerminalFaxNo": "000-000-0000",
        "DestTerminalFreePhone": "800-610-6500",
        "DestTerminalName": "WEST PALM BEACH",
        "DestTerminalPhoneNo": "561-735-0988",
        "DestTerminalState": "FL",
        "DestTerminalZip": "33426",
        "DestTerminalZipCode": "33426",
        "Discount": 1272.06,
        "DiscountID": 0,
        "DiscountRate": 0,
        "EquipmentCharges": null,
        "Equipments": null,
        "ExcludeReason": "",
        "FreightCost": 153.77,
        "FuelCost": 31.76,
        "FuelRate": 0,
        "GrossAmount": 1425.83,
        "IsClientGainShare": false,
        "IsExcluded": true,
        "IsMinimumApplied": false,
        "IsVendorPortalRate": false,
        "LaneID": 479709,
        "LaneName": "YRC - STD - US-US - BLANKET API",
        "LaneWiseMiles": 1230,
        "MaxHeightShipmentLimit": "Max Height :8 Feet",
        "MaxLenghtShipmentLimit": "Max Length :11 linear Feet",
        "Miles": 1230,
        "MinAmount": 0,
        "ModeType": null,
        "NewInsuranceCost": 0,
        "OldInsuranceCost": 0,
        "OriginTerminalAddress1": "12340 E NORTHWEST HWY",
        "OriginTerminalAddress2": "-",
        "OriginTerminalCity": "DALLAS",
        "OriginTerminalCode": "508",
        "OriginTerminalContactName": "NOTT",
        "OriginTerminalContactTitle": "-",
        "OriginTerminalEmail": "-",
        "OriginTerminalFaxNo": "877-667-9425",
        "OriginTerminalFreePhone": "800-610-6500",
        "OriginTerminalName": "GARLAND",
        "OriginTerminalPhoneNo": "214-819-4578",
        "OriginTerminalState": "TX",
        "OriginTerminalZip": "75228",
        "OriginTerminalZipCode": "75228",
        "PaymentType": "Prepaid",
        "Products": [
          {
            "FAKClass": 0,
            "HazMat": false,
            "Height": 48,
            "Length": 48,
            "NmfcNumber": null,
            "PackageType": null,
            "PackageTypeID": null,
            "Pallets": 0,
            "Pieces": 1,
            "ProductClass": 50,
            "ProductCost": 0,
            "ProductDescription": null,
            "RateBase": 0,
            "Stackable": false,
            "Weight": 1000,
            "Width": 48
          }
        ],
        "ProfileID": 11868,
        "QuoteNumber": "",
        "RateType": "CarrierRateService",
        "RatingMarkUp": null,
        "RatingResultId": 57060374,
        "ReferenceNo": 30,
        "Remarks": null,
        "SAASQuoteNumber": 61359355,
        "SaasBrokerCarrierCode": null,
        "SaasBrokerCarrierName": null,
        "SaasServiceLevelCode": "STD",
        "ServiceLevel": "Standard",
        "ServiceLevelCode": null,
        "ShowTrueCost": false,
        "StatusCode": 1,
        "TariffName": null,
        "TotalAccCost": 0,
        "TotalAccCostWithOutTrueCost": 0,
        "TotalCost": 185.53,
        "TotalCostWithCustCostWithOutTrueCost": 185.53,
        "TotalCostWithOutTrueCost": 185.53,
        "TotalShipmentCostWithCustomerCost": 185.53,
        "TransitTime": "3",
        "UsedRatingFuel": {
          "EffectiveFrom": "/Date(662706000000-0500)/",
          "EffectiveTo": "/Date(662706000000-0500)/",
          "FuelLevel": null,
          "FuelRate": 0,
          "FuelRateType": "0",
          "MaxRate": 0,
          "Message": "",
          "MinRate": 0
        },
        "UsedRatingWeeklyFuel": null,
        "ZoneAreaID": 0,
        "ZoneID": 0,
        "ZoneRateID": 0
      },
      {
        "Accessorials": [
          {
            "AccessorialCharge": 0,
            "AccessorialCode": "XSS",
            "AccessorialDescription": "XSS",
            "AccessorialID": -1,
            "AccessorialLevel": null,
            "AccessorialRate": 0,
            "AccessorialType": 0,
            "IsIncluded": false,
            "IsNotRated": false,
            "IsSystem": false,
            "Message": null,
            "ShowTrueCost": true,
            "WeightFrom": 0,
            "WeightTo": 0
          }
        ],
        "ApiCallDuration": "00:00:01.3125828",
        "BenchMarkCost": null,
        "CarrierConnectRequestResponseString": null,
        "CarrierCost": 194.54,
        "CarrierCostWithOutTrueCost": 194.54,
        "CarrierID": "CNWY",
        "CarrierName": "XPO LOGISTICS",
        "CarrierType": "Direct",
        "CarrierTypeID": 2,
        "CostWithCustomerPercentage": 0,
        "CostWithCustomerPercentageWithOutTrueCost": 0,
        "CustomerCost": 0,
        "DeficitCharge": 0,
        "DeficitWeight": 0,
        "DestTerminalAddress1": "1301 W 15TH ST",
        "DestTerminalAddress2": "XPO LOGISTICS FREIGHT, INC.",
        "DestTerminalCity": "RIVIERA BEACH",
        "DestTerminalCode": "NWF",
        "DestTerminalContactName": "-",
        "DestTerminalContactTitle": "MANAGER",
        "DestTerminalEmail": "-",
        "DestTerminalFaxNo": "561-845-3963",
        "DestTerminalFreePhone": "800-221-3375",
        "DestTerminalName": "WEST PALM BEACH FL",
        "DestTerminalPhoneNo": "561-842-1971",
        "DestTerminalState": "FL",
        "DestTerminalZip": "33404",
        "DestTerminalZipCode": "33404",
        "Discount": 253.39,
        "DiscountID": 0,
        "DiscountRate": 0,
        "EquipmentCharges": null,
        "Equipments": null,
        "ExcludeReason": "",
        "FreightCost": 161.24,
        "FuelCost": 33.3,
        "FuelRate": 0,
        "GrossAmount": 414.63,
        "IsClientGainShare": false,
        "IsExcluded": true,
        "IsMinimumApplied": false,
        "IsVendorPortalRate": false,
        "LaneID": 1565302,
        "LaneName": "CNWY - STD - US-US - BLANKET API",
        "LaneWiseMiles": 1230,
        "MaxHeightShipmentLimit": "Max Height :8 Feet",
        "MaxLenghtShipmentLimit": "Max Length :14 linear Feet",
        "Miles": 1230,
        "MinAmount": 0,
        "ModeType": null,
        "NewInsuranceCost": 1000,
        "OldInsuranceCost": 1000,
        "OriginTerminalAddress1": "530 S INTERNATIONAL RD",
        "OriginTerminalAddress2": "XPO LOGISTICS FREIGHT, INC.",
        "OriginTerminalCity": "GARLAND",
        "OriginTerminalCode": "LGT",
        "OriginTerminalContactName": "-",
        "OriginTerminalContactTitle": "MANAGER",
        "OriginTerminalEmail": "-",
        "OriginTerminalFaxNo": "972-487-1334",
        "OriginTerminalFreePhone": "800-523-4997",
        "OriginTerminalName": "GARLAND TX",
        "OriginTerminalPhoneNo": "972-487-8863",
        "OriginTerminalState": "TX",
        "OriginTerminalZip": "75042",
        "OriginTerminalZipCode": "75042",
        "PaymentType": "Prepaid",
        "Products": [
          {
            "FAKClass": 50,
            "HazMat": false,
            "Height": 48,
            "Length": 48,
            "NmfcNumber": null,
            "PackageType": null,
            "PackageTypeID": null,
            "Pallets": 0,
            "Pieces": 1,
            "ProductClass": 50,
            "ProductCost": 0,
            "ProductDescription": null,
            "RateBase": 0,
            "Stackable": false,
            "Weight": 1000,
            "Width": 48
          }
        ],
        "ProfileID": 11868,
        "QuoteNumber": "5507902865908",
        "RateType": "CarrierRateService",
        "RatingMarkUp": null,
        "RatingResultId": 57060355,
        "ReferenceNo": 9,
        "Remarks": null,
        "SAASQuoteNumber": 61359355,
        "SaasBrokerCarrierCode": null,
        "SaasBrokerCarrierName": null,
        "SaasServiceLevelCode": "STD",
        "ServiceLevel": "Standard",
        "ServiceLevelCode": null,
        "ShowTrueCost": false,
        "StatusCode": 1,
        "TariffName": null,
        "TotalAccCost": 0,
        "TotalAccCostWithOutTrueCost": 0,
        "TotalCost": 194.54,
        "TotalCostWithCustCostWithOutTrueCost": 194.54,
        "TotalCostWithOutTrueCost": 194.54,
        "TotalShipmentCostWithCustomerCost": 194.54,
        "TransitTime": "2",
        "UsedRatingFuel": {
          "EffectiveFrom": "/Date(662706000000-0500)/",
          "EffectiveTo": "/Date(662706000000-0500)/",
          "FuelLevel": null,
          "FuelRate": 0,
          "FuelRateType": "0",
          "MaxRate": 0,
          "Message": "",
          "MinRate": 0
        },
        "UsedRatingWeeklyFuel": null,
        "ZoneAreaID": 0,
        "ZoneID": 0,
        "ZoneRateID": 0
      },
      {
        "Accessorials": [],
        "ApiCallDuration": "00:00:00.7812430",
        "BenchMarkCost": null,
        "CarrierConnectRequestResponseString": null,
        "CarrierCost": 202.23,
        "CarrierCostWithOutTrueCost": 202.23,
        "CarrierID": "DYLT",
        "CarrierName": "DAYLIGHT TRANSPORT",
        "CarrierType": "Direct",
        "CarrierTypeID": 0,
        "CostWithCustomerPercentage": 0,
        "CostWithCustomerPercentageWithOutTrueCost": 0,
        "CustomerCost": 0,
        "DeficitCharge": 0,
        "DeficitWeight": 0,
        "DestTerminalAddress1": "-",
        "DestTerminalAddress2": "SUITE 200",
        "DestTerminalCity": "LONG BEACH",
        "DestTerminalCode": "MIS02",
        "DestTerminalContactName": "ALMA MAZO",
        "DestTerminalContactTitle": "BUSINESS DEVELOPMENT SPECIALIST",
        "DestTerminalEmail": "AMAZO@DYLT.COM",
        "DestTerminalFaxNo": "866-814-3091",
        "DestTerminalFreePhone": "800-468-9999",
        "DestTerminalName": "DAYLIGHT TRANSPORT",
        "DestTerminalPhoneNo": "310-507-8200",
        "DestTerminalState": "CA",
        "DestTerminalZip": "90810",
        "DestTerminalZipCode": "90810",
        "Discount": 2161.85,
        "DiscountID": 0,
        "DiscountRate": 0,
        "EquipmentCharges": null,
        "Equipments": null,
        "ExcludeReason": "",
        "FreightCost": 167.69,
        "FuelCost": 34.54,
        "FuelRate": 0,
        "GrossAmount": 2329.54,
        "IsClientGainShare": false,
        "IsExcluded": true,
        "IsMinimumApplied": false,
        "IsVendorPortalRate": false,
        "LaneID": 332203,
        "LaneName": "DAYLIGHT - STD - US-US - BLANKET API",
        "LaneWiseMiles": 1230,
        "MaxHeightShipmentLimit": "Max Height :12 Feet",
        "MaxLenghtShipmentLimit": "Max Length :20 linear Feet",
        "Miles": 1230,
        "MinAmount": 0,
        "ModeType": null,
        "NewInsuranceCost": 2000,
        "OldInsuranceCost": 500,
        "OriginTerminalAddress1": "-",
        "OriginTerminalAddress2": "SUITE 200",
        "OriginTerminalCity": "LONG BEACH",
        "OriginTerminalCode": "DAL01",
        "OriginTerminalContactName": "ALMA MAZO",
        "OriginTerminalContactTitle": "BUSINESS DEVELOPMENT SPECIALIST",
        "OriginTerminalEmail": "AMAZO@DYLT.COM",
        "OriginTerminalFaxNo": "866-814-3091",
        "OriginTerminalFreePhone": "800-468-9999",
        "OriginTerminalName": "DAYLIGHT TRANSPORT",
        "OriginTerminalPhoneNo": "310-507-8200",
        "OriginTerminalState": "CA",
        "OriginTerminalZip": "90810",
        "OriginTerminalZipCode": "90810",
        "PaymentType": "Prepaid",
        "Products": [
          {
            "FAKClass": 0,
            "HazMat": false,
            "Height": 48,
            "Length": 48,
            "NmfcNumber": null,
            "PackageType": null,
            "PackageTypeID": null,
            "Pallets": 0,
            "Pieces": 1,
            "ProductClass": 50,
            "ProductCost": 0,
            "ProductDescription": null,
            "RateBase": 0,
            "Stackable": false,
            "Weight": 1000,
            "Width": 48
          }
        ],
        "ProfileID": 11868,
        "QuoteNumber": "CQ17455766",
        "RateType": "CarrierRateService",
        "RatingMarkUp": null,
        "RatingResultId": 57060357,
        "ReferenceNo": 16,
        "Remarks": null,
        "SAASQuoteNumber": 61359355,
        "SaasBrokerCarrierCode": null,
        "SaasBrokerCarrierName": null,
        "SaasServiceLevelCode": "STD",
        "ServiceLevel": "Standard",
        "ServiceLevelCode": null,
        "ShowTrueCost": false,
        "StatusCode": 1,
        "TariffName": null,
        "TotalAccCost": 0,
        "TotalAccCostWithOutTrueCost": 0,
        "TotalCost": 202.23,
        "TotalCostWithCustCostWithOutTrueCost": 202.23,
        "TotalCostWithOutTrueCost": 202.23,
        "TotalShipmentCostWithCustomerCost": 202.23,
        "TransitTime": "2",
        "UsedRatingFuel": {
          "EffectiveFrom": "/Date(662706000000-0500)/",
          "EffectiveTo": "/Date(662706000000-0500)/",
          "FuelLevel": null,
          "FuelRate": 0,
          "FuelRateType": "0",
          "MaxRate": 0,
          "Message": "",
          "MinRate": 0
        },
        "UsedRatingWeeklyFuel": null,
        "ZoneAreaID": 0,
        "ZoneID": 0,
        "ZoneRateID": 0
      },
      {
        "Accessorials": [
          {
            "AccessorialCharge": 40,
            "AccessorialCode": "MIS",
            "AccessorialDescription": "GUARANTEED SERVICE",
            "AccessorialID": -1,
            "AccessorialLevel": null,
            "AccessorialRate": 0,
            "AccessorialType": 0,
            "IsIncluded": false,
            "IsNotRated": false,
            "IsSystem": false,
            "Message": null,
            "ShowTrueCost": true,
            "WeightFrom": 0,
            "WeightTo": 0
          }
        ],
        "ApiCallDuration": "00:00:01.1093653",
        "BenchMarkCost": null,
        "CarrierConnectRequestResponseString": null,
        "CarrierCost": 208.87,
        "CarrierCostWithOutTrueCost": 208.87,
        "CarrierID": "SEFL",
        "CarrierName": "SOUTHEASTERN FREIGHT LINES",
        "CarrierType": "Direct",
        "CarrierTypeID": 2,
        "CostWithCustomerPercentage": 0,
        "CostWithCustomerPercentageWithOutTrueCost": 0,
        "CustomerCost": 0,
        "DeficitCharge": 0,
        "DeficitWeight": 0,
        "DestTerminalAddress1": "201 AVENUE P",
        "DestTerminalAddress2": "-",
        "DestTerminalCity": "RIVIERA BEACH",
        "DestTerminalCode": "WPB",
        "DestTerminalContactName": "NICK CRAWFORD",
        "DestTerminalContactTitle": "TERMINAL MANAGER",
        "DestTerminalEmail": "nicholas.crawford@sefl.com",
        "DestTerminalFaxNo": "561-848-2632",
        "DestTerminalFreePhone": "800-282-7335",
        "DestTerminalName": "WEST PALM BEACH",
        "DestTerminalPhoneNo": "561-881-9980",
        "DestTerminalState": "FL",
        "DestTerminalZip": "33404",
        "DestTerminalZipCode": "33404",
        "Discount": 99.05,
        "DiscountID": 0,
        "DiscountRate": 0,
        "EquipmentCharges": null,
        "Equipments": null,
        "ExcludeReason": "",
        "FreightCost": 146.46,
        "FuelCost": 22.41,
        "FuelRate": 0,
        "GrossAmount": 245.51,
        "IsClientGainShare": false,
        "IsExcluded": true,
        "IsMinimumApplied": false,
        "IsVendorPortalRate": false,
        "LaneID": 366760,
        "LaneName": "SEFL - GUA -US-US - BLANKET API",
        "LaneWiseMiles": 1230,
        "MaxHeightShipmentLimit": "Max Height :8 Feet",
        "MaxLenghtShipmentLimit": "Max Length :12 linear Feet",
        "Miles": 1230,
        "MinAmount": 0,
        "ModeType": null,
        "NewInsuranceCost": 990,
        "OldInsuranceCost": 100,
        "OriginTerminalAddress1": "3301 WEST MILLER ROAD",
        "OriginTerminalAddress2": "-",
        "OriginTerminalCity": "GARLAND",
        "OriginTerminalCode": "GAR",
        "OriginTerminalContactName": "KEVIN OWENS",
        "OriginTerminalContactTitle": "TERMINAL MANAGER",
        "OriginTerminalEmail": "KEVIN.M.OWENS@SEFL.COM",
        "OriginTerminalFaxNo": "972-271-0804",
        "OriginTerminalFreePhone": "855-782-7335",
        "OriginTerminalName": "GARLAND",
        "OriginTerminalPhoneNo": "972-271-0770",
        "OriginTerminalState": "TX",
        "OriginTerminalZip": "75041",
        "OriginTerminalZipCode": "75041",
        "PaymentType": "Prepaid",
        "Products": [
          {
            "FAKClass": 0,
            "HazMat": false,
            "Height": 48,
            "Length": 48,
            "NmfcNumber": null,
            "PackageType": null,
            "PackageTypeID": null,
            "Pallets": 0,
            "Pieces": 1,
            "ProductClass": 50,
            "ProductCost": 0,
            "ProductDescription": null,
            "RateBase": 0,
            "Stackable": false,
            "Weight": 1000,
            "Width": 48
          }
        ],
        "ProfileID": 11868,
        "QuoteNumber": "CXFTC97C2",
        "RateType": "CarrierRateService",
        "RatingMarkUp": null,
        "RatingResultId": 57060367,
        "ReferenceNo": 29,
        "Remarks": null,
        "SAASQuoteNumber": 61359355,
        "SaasBrokerCarrierCode": null,
        "SaasBrokerCarrierName": null,
        "SaasServiceLevelCode": "GTS",
        "ServiceLevel": "Guaranteed",
        "ServiceLevelCode": null,
        "ShowTrueCost": false,
        "StatusCode": 1,
        "TariffName": null,
        "TotalAccCost": 40,
        "TotalAccCostWithOutTrueCost": 40,
        "TotalCost": 208.87,
        "TotalCostWithCustCostWithOutTrueCost": 208.87,
        "TotalCostWithOutTrueCost": 208.87,
        "TotalShipmentCostWithCustomerCost": 208.87,
        "TransitTime": "2",
        "UsedRatingFuel": {
          "EffectiveFrom": "/Date(662706000000-0500)/",
          "EffectiveTo": "/Date(662706000000-0500)/",
          "FuelLevel": null,
          "FuelRate": 0,
          "FuelRateType": "0",
          "MaxRate": 0,
          "Message": "",
          "MinRate": 0
        },
        "UsedRatingWeeklyFuel": null,
        "ZoneAreaID": 0,
        "ZoneID": 0,
        "ZoneRateID": 0
      },
      {
        "Accessorials": [
          {
            "AccessorialCharge": 34,
            "AccessorialCode": "MIS",
            "AccessorialDescription": "GDEL",
            "AccessorialID": -1,
            "AccessorialLevel": null,
            "AccessorialRate": 0,
            "AccessorialType": 0,
            "IsIncluded": false,
            "IsNotRated": false,
            "IsSystem": false,
            "Message": null,
            "ShowTrueCost": true,
            "WeightFrom": 0,
            "WeightTo": 0
          }
        ],
        "ApiCallDuration": "00:00:02.2031555",
        "BenchMarkCost": null,
        "CarrierConnectRequestResponseString": null,
        "CarrierCost": 226.55,
        "CarrierCostWithOutTrueCost": 226.55,
        "CarrierID": "YFSY",
        "CarrierName": "YRC FREIGHT",
        "CarrierType": "Direct",
        "CarrierTypeID": 2,
        "CostWithCustomerPercentage": 0,
        "CostWithCustomerPercentageWithOutTrueCost": 0,
        "CustomerCost": 0,
        "DeficitCharge": 0,
        "DeficitWeight": 0,
        "DestTerminalAddress1": "1400 SW 30TH AVE",
        "DestTerminalAddress2": "-",
        "DestTerminalCity": "BOYNTON BEACH",
        "DestTerminalCode": "757",
        "DestTerminalContactName": "DAVIS",
        "DestTerminalContactTitle": "-",
        "DestTerminalEmail": "-",
        "DestTerminalFaxNo": "000-000-0000",
        "DestTerminalFreePhone": "800-610-6500",
        "DestTerminalName": "WEST PALM BEACH",
        "DestTerminalPhoneNo": "561-735-0988",
        "DestTerminalState": "FL",
        "DestTerminalZip": "33426",
        "DestTerminalZipCode": "33426",
        "Discount": 1272.06,
        "DiscountID": 0,
        "DiscountRate": 0,
        "EquipmentCharges": null,
        "Equipments": null,
        "ExcludeReason": "",
        "FreightCost": 153.28,
        "FuelCost": 39.27,
        "FuelRate": 0,
        "GrossAmount": 1425.34,
        "IsClientGainShare": false,
        "IsExcluded": true,
        "IsMinimumApplied": false,
        "IsVendorPortalRate": false,
        "LaneID": 697743,
        "LaneName": "YRC - GUA PM - US-US - BLANKET API",
        "LaneWiseMiles": 1230,
        "MaxHeightShipmentLimit": "Max Height :8 Feet",
        "MaxLenghtShipmentLimit": "Max Length :11 linear Feet",
        "Miles": 1230,
        "MinAmount": 0,
        "ModeType": null,
        "NewInsuranceCost": 0,
        "OldInsuranceCost": 0,
        "OriginTerminalAddress1": "12340 E NORTHWEST HWY",
        "OriginTerminalAddress2": "-",
        "OriginTerminalCity": "DALLAS",
        "OriginTerminalCode": "508",
        "OriginTerminalContactName": "NOTT",
        "OriginTerminalContactTitle": "-",
        "OriginTerminalEmail": "-",
        "OriginTerminalFaxNo": "877-667-9425",
        "OriginTerminalFreePhone": "800-610-6500",
        "OriginTerminalName": "GARLAND",
        "OriginTerminalPhoneNo": "214-819-4578",
        "OriginTerminalState": "TX",
        "OriginTerminalZip": "75228",
        "OriginTerminalZipCode": "75228",
        "PaymentType": "Prepaid",
        "Products": [
          {
            "FAKClass": 0,
            "HazMat": false,
            "Height": 48,
            "Length": 48,
            "NmfcNumber": null,
            "PackageType": null,
            "PackageTypeID": null,
            "Pallets": 0,
            "Pieces": 1,
            "ProductClass": 50,
            "ProductCost": 0,
            "ProductDescription": null,
            "RateBase": 0,
            "Stackable": false,
            "Weight": 1000,
            "Width": 48
          }
        ],
        "ProfileID": 11868,
        "QuoteNumber": "",
        "RateType": "CarrierRateService",
        "RatingMarkUp": null,
        "RatingResultId": 57060372,
        "ReferenceNo": 31,
        "Remarks": null,
        "SAASQuoteNumber": 61359355,
        "SaasBrokerCarrierCode": null,
        "SaasBrokerCarrierName": null,
        "SaasServiceLevelCode": "EXP",
        "ServiceLevel": "Guaranteed by 5:00 p.m. on  the standard delivery date",
        "ServiceLevelCode": null,
        "ShowTrueCost": false,
        "StatusCode": 1,
        "TariffName": null,
        "TotalAccCost": 34,
        "TotalAccCostWithOutTrueCost": 34,
        "TotalCost": 226.55,
        "TotalCostWithCustCostWithOutTrueCost": 226.55,
        "TotalCostWithOutTrueCost": 226.55,
        "TotalShipmentCostWithCustomerCost": 226.55,
        "TransitTime": "3",
        "UsedRatingFuel": {
          "EffectiveFrom": "/Date(662706000000-0500)/",
          "EffectiveTo": "/Date(662706000000-0500)/",
          "FuelLevel": null,
          "FuelRate": 0,
          "FuelRateType": "0",
          "MaxRate": 0,
          "Message": "",
          "MinRate": 0
        },
        "UsedRatingWeeklyFuel": null,
        "ZoneAreaID": 0,
        "ZoneID": 0,
        "ZoneRateID": 0
      },
      {
        "Accessorials": [
          {
            "AccessorialCharge": 53.5,
            "AccessorialCode": "MIS",
            "AccessorialDescription": "GuaranteedDeliveryFee",
            "AccessorialID": -1,
            "AccessorialLevel": null,
            "AccessorialRate": 0,
            "AccessorialType": 0,
            "IsIncluded": false,
            "IsNotRated": false,
            "IsSystem": false,
            "Message": null,
            "ShowTrueCost": true,
            "WeightFrom": 0,
            "WeightTo": 0
          }
        ],
        "ApiCallDuration": "00:00:04.5781924",
        "BenchMarkCost": null,
        "CarrierConnectRequestResponseString": null,
        "CarrierCost": 238.86,
        "CarrierCostWithOutTrueCost": 238.86,
        "CarrierID": "AACT",
        "CarrierName": "AAA COOPER TRANSPORTATION",
        "CarrierType": "Direct",
        "CarrierTypeID": 2,
        "CostWithCustomerPercentage": 0,
        "CostWithCustomerPercentageWithOutTrueCost": 0,
        "CustomerCost": 0,
        "DeficitCharge": 0,
        "DeficitWeight": 0,
        "DestTerminalAddress1": "7511 COMMERCIAL CIRCLE",
        "DestTerminalAddress2": "-",
        "DestTerminalCity": "FORT PIERCE",
        "DestTerminalCode": "FPR",
        "DestTerminalContactName": "MARK BRADY",
        "DestTerminalContactTitle": "TERMINAL MANAGER",
        "DestTerminalEmail": "MARK.BRADY@AAACOOPER.COM",
        "DestTerminalFaxNo": "855-206-4853",
        "DestTerminalFreePhone": "800-252-0246",
        "DestTerminalName": "FORT PIERCE",
        "DestTerminalPhoneNo": "772-429-2797",
        "DestTerminalState": "FL",
        "DestTerminalZip": "34951",
        "DestTerminalZipCode": "34951",
        "Discount": 1638.62,
        "DiscountID": 0,
        "DiscountRate": 0,
        "EquipmentCharges": null,
        "Equipments": null,
        "ExcludeReason": "",
        "FreightCost": 155.24,
        "FuelCost": 30.12,
        "FuelRate": 0,
        "GrossAmount": 1793.86,
        "IsClientGainShare": false,
        "IsExcluded": true,
        "IsMinimumApplied": false,
        "IsVendorPortalRate": false,
        "LaneID": 1553539,
        "LaneName": "AACT - Blanket Pricing - GUA - USA - USA",
        "LaneWiseMiles": 1230,
        "MaxHeightShipmentLimit": "Max Height :8 Feet",
        "MaxLenghtShipmentLimit": "Max Length :12 linear Feet",
        "Miles": 1230,
        "MinAmount": 0,
        "ModeType": null,
        "NewInsuranceCost": 990,
        "OldInsuranceCost": 100,
        "OriginTerminalAddress1": "311 WEST TRINITY BLVD",
        "OriginTerminalAddress2": "-",
        "OriginTerminalCity": "GRAND PRAIRIE",
        "OriginTerminalCode": "DAL",
        "OriginTerminalContactName": "JACOB BASS",
        "OriginTerminalContactTitle": "TERMINAL MANAGER",
        "OriginTerminalEmail": "JACOB.BASS@AAACOOPER.COM",
        "OriginTerminalFaxNo": "855-261-7682",
        "OriginTerminalFreePhone": "800-354-2465",
        "OriginTerminalName": "DALLAS",
        "OriginTerminalPhoneNo": "972-266-9045",
        "OriginTerminalState": "TX",
        "OriginTerminalZip": "75050",
        "OriginTerminalZipCode": "75050",
        "PaymentType": "Prepaid",
        "Products": [
          {
            "FAKClass": 0,
            "HazMat": false,
            "Height": 48,
            "Length": 48,
            "NmfcNumber": null,
            "PackageType": null,
            "PackageTypeID": null,
            "Pallets": 0,
            "Pieces": 1,
            "ProductClass": 50,
            "ProductCost": 0,
            "ProductDescription": null,
            "RateBase": 0,
            "Stackable": false,
            "Weight": 1000,
            "Width": 48
          }
        ],
        "ProfileID": 11868,
        "QuoteNumber": "006156501",
        "RateType": "CarrierRateService",
        "RatingMarkUp": null,
        "RatingResultId": 57060377,
        "ReferenceNo": 40,
        "Remarks": null,
        "SAASQuoteNumber": 61359355,
        "SaasBrokerCarrierCode": null,
        "SaasBrokerCarrierName": null,
        "SaasServiceLevelCode": "GTS",
        "ServiceLevel": "GuaranteedDeliveryFee",
        "ServiceLevelCode": null,
        "ShowTrueCost": false,
        "StatusCode": 1,
        "TariffName": null,
        "TotalAccCost": 53.5,
        "TotalAccCostWithOutTrueCost": 53.5,
        "TotalCost": 238.86,
        "TotalCostWithCustCostWithOutTrueCost": 238.86,
        "TotalCostWithOutTrueCost": 238.86,
        "TotalShipmentCostWithCustomerCost": 238.86,
        "TransitTime": "3",
        "UsedRatingFuel": {
          "EffectiveFrom": "/Date(662706000000-0500)/",
          "EffectiveTo": "/Date(662706000000-0500)/",
          "FuelLevel": null,
          "FuelRate": 0,
          "FuelRateType": "0",
          "MaxRate": 0,
          "Message": "",
          "MinRate": 0
        },
        "UsedRatingWeeklyFuel": null,
        "ZoneAreaID": 0,
        "ZoneID": 0,
        "ZoneRateID": 0
      }
    ];
  }
}
