// Generated by https://quicktype.io

export interface GetLocationsParameters {
    ClientId:    number;
    IsAccending: boolean;
    LocationID:  null;
    Name: string;
    ShortName: string;
    ContactName: string;
    ContactEmail: string;
    ContactPhone: string;
    OrderBy:     string;
    PageNumber:  number;
    PageSize:    number;
    Status:      null;
}
