// Generated by https://quicktype.io

export interface GetLocationsParameters {
    ClientId:    number;
    IsAccending: boolean;
    LocationID:  null;
    OrderBy:     string;
    PageNumber:  number;
    PageSize:    number;
    Status:      null;
}
