export class MasUser {
  Address: string;
  Address2: string;
  BranchCode: string;
  CityId: number;
  CityName: string;
  ClientId: number;
  ContactEmail: string;
  ContactPhone: string;
  ContactName: string;
  CountryID: number;
  CountryName: string;
  FirstName: string;
  GroupID: number;
  IsShowAllClient: boolean;
  IsSystem: boolean;
  IsUsedStaticToken: boolean;
  LastName: string;
  LoginTryCount: number;
  PODCode: string;
  PODId: number;
  PODName: string;
  ParentUserID: number;
  Password: string;
  PostalCode: string;
  PostalId: number;
  SalesPersonCode: string;
  SalesRep: any;
  StateID: number;
  StateName: string;
  Status: any;
  TenderEmail: string;
  UserGroupID: any;
  UserInGroupId: any;
  UserNickName: string;
  UserRowId: number;
  UserToken: string;
  UserType: any;
  UserTypeID: number;

  constructor(masUser?: any) {
    this.Address = masUser && masUser.Address ? masUser.Address : null;
    this.Address2 = masUser && masUser.Address2 ? masUser.Address2 : null;
    this.BranchCode = masUser && masUser.BranchCode ? masUser.BranchCode : null;
    this.CityId = masUser && masUser.CityId ? masUser.CityId : null;
    this.CityName = masUser && masUser.CityName ? masUser.CityName : null;
    this.ClientId = masUser && masUser.ClientId ? masUser.ClientId : null;
    this.ContactEmail = masUser && masUser.ContactEmail ? masUser.ContactEmail : null;
    this.ContactName = masUser && masUser.ContactName ? masUser.ContactName : null;
    this.ContactPhone = masUser && masUser.ContactPhone ? masUser.ContactPhone : null;
    this.CountryID = masUser && masUser.CountryID ? masUser.CountryID : null;
    this.CountryName = masUser && masUser.CountryName ? masUser.CountryName : null;
    this.FirstName = masUser && masUser.FirstName ? masUser.FirstName : null;
    this.GroupID = masUser && masUser.GroupID ? masUser.GroupID : null;
    this.IsShowAllClient = masUser && masUser.IsShowAllClient !== null ? masUser.IsShowAllClient : null;
    this.IsSystem = masUser && masUser.IsSystem !== null ? masUser.IsSystem : null;
    this.IsUsedStaticToken = masUser && masUser.IsUsedStaticToken !== null ? masUser.IsUsedStaticToken : null;
    this.LastName = masUser && masUser.LastName ? masUser.LastName : null;
    this.LoginTryCount = masUser && masUser.LoginTryCount ? masUser.LoginTryCount : null;
    this.PODCode = masUser && masUser.PODCode ? masUser.PODCode : null;
    this.PODId = masUser && masUser.PODId ? masUser.PODId : null;
    this.PODName = masUser && masUser.PODName ? masUser.PODName : null;
    this.ParentUserID = masUser && masUser.ParentUserID ? masUser.ParentUserID : null;
    this.Password = masUser && masUser.Password ? masUser.Password : null;
    this.PostalCode = masUser && masUser.PostalCode ? masUser.PostalCode : null;
    this.PostalId = masUser && masUser.PostalId ? masUser.PostalId : null;
    this.SalesPersonCode = masUser && masUser.SalesPersonCode ? masUser.SalesPersonCode : null;
    this.SalesRep = masUser && masUser.SalesRep ? masUser.SalesRep : null;
    this.StateID = masUser && masUser.StateID ? masUser.StateID : null;
    this.StateName = masUser && masUser.StateName ? masUser.StateName : null;
    this.Status = masUser && masUser.Status !== null ? masUser.Status : null;
    this.TenderEmail = masUser && masUser.TenderEmail ? masUser.TenderEmail : null;
    this.UserGroupID = masUser && masUser.UserGroupID ? masUser.UserGroupID : null;
    this.UserInGroupId = masUser && masUser.UserInGroupId ? masUser.UserInGroupId : null;
    this.UserNickName = masUser && masUser.UserNickName ? masUser.UserNickName : null;
    this.UserRowId = masUser && masUser.UserRowId ? masUser.UserRowId : null;
    this.UserToken = masUser && masUser.UserToken ? masUser.UserToken : null;
    this.UserType = masUser && masUser.UserType ? masUser.UserType : null;
    this.UserTypeID = masUser && masUser.UserTypeID ? masUser.UserTypeID : null;
  }
}
