// Generated by https://quicktype.io
export class Quote {
    ActualDeliveryDate:    string;
    ActualShipDate:        string;
    BOLStatus:             string;
    BolStatusSeq:          number;
    CarrierName:           string;
    ClientID:              number;
    ClientLadingNo:        string;
    ClientName:            string;
    DestName:              string;
    DestinationLocation:   string;
    EquipmentDescription:  string;
    ErrorDescription:      string;
    ExpectedDeliveryDate:  string;
    ExpectedShipDate:      string;
    IsAljexEDIGenerated:   null;
    IsEDIGenerated:        null;
    LadingID:              number;
    Mode:                  string;
    OldBolStatusID:        number;
    OrgName:               string;
    OriginLocation:        string;
    PickupApiCallStatusId: null;
    ProNumber:             string;
    QuoteNumber:           string;
    Stackable:             null;
    Status:                number;
    TotalRowCount:         number;
    TransitDays:            string;

    get ActualShipDateWithFormat(){
        let actualShipDate = '';

        actualShipDate = 'A'; //this.ActualShipDate.replace(/(^.*\()|([+-].*$)/g, '')'';

        return 'A';
    }

    set ActualShipDateWithFormat(value){
    }

}
